import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from "@angular/core";
import { FormBuilder, ReactiveFormsModule, Validators } from "@angular/forms";
import { firstValueFrom } from "rxjs";
import { ColDef, RowData } from "ag-grid-community";
import { DataGrid } from "../../../../../shared/components/data-grid/data-grid";
import { ModalComponent } from "../../../../../shared/components/modal/modal.component";
import { SelectInput } from "../../../../../shared/components/select-input/select-input";
import { InputField } from "../../../../../shared/components/input-field/input-field";
import { ExportKind, ExportToolbar } from "../../../../../shared/components/export-toolbar/export-toolbar";
import { ToolbarSearch } from "../../../../../shared/components/toolbar-search/toolbar-search";
import { IconComponent } from "../../../../../shared/components/icon/icon.component";
import { HelpGuidance } from "../../../shared/components/help-guidance/help-guidance";
import { PrintColumn, ReportExportService } from "../../../../../Core/services/generic-export-service/generic-export.service";
import { ObsApiService } from "../../services/obs-api.service";
import { NotificationService } from "../../../../../Core/services/notification/notification.service";
import { ParentInventory } from "../../models/requisition.model";
import { IifEntry } from "../../models/transaction.model";

const PARENT_INVENTORY_OPTIONS: { label: string; value: ParentInventory }[] = [
  { label: "ILMS (MO)", value: "ILMS" },
  { label: "WLMS (WED)", value: "WLMS" },
];

type SpareCategoryFilter = "PERMANENT" | "RETURNABLE" | "CONSUMABLE";
const CATEGORY_FILTER_OPTIONS: { key: SpareCategoryFilter; label: string }[] = [
  { key: "PERMANENT", label: "Permanent" },
  { key: "RETURNABLE", label: "Returnable" },
  { key: "CONSUMABLE", label: "Consumable" },
];

const HELP_HTML = `
  <h6 class="fw-bold mb-1">What this page is for</h6>
  <p class="mb-2">This cart holds every spare whose pattern number was auto-generated by SWMM during
     your first inventory import — the ones where the pattern-number cell was left empty, or the
     number did not match the ILMS/WLMS databases. These items cannot go for survey or demand yet;
     their pattern number must be settled first.</p>
  <h6 class="fw-bold mb-1">Two ways to clear an item from this cart</h6>
  <ol class="mb-2">
    <li><strong>Correct the pattern number</strong> — open the row's Edit Pattern Number box, type
        the correct pattern number, and press <strong>Verify</strong>. SWMM checks it against the
        ILMS and WLMS databases; if it matches, save it. On the next page refresh the item leaves
        this cart on its own and moves to the Survey cart or Demand cart.</li>
    <li><strong>Send it for incatting</strong> — if you cannot find the correct pattern number, tick
        the item, pick the Parent Inventory (ILMS or WLMS), and press
        <strong>Send to MO/WED IIF Cart</strong>. The item goes to the IIF cart inside the MO / WED
        Inventory module, where Ship Staff do the incatting. Once incatting is done, Ship Staff press
        Check Incatting Status in that IIF cart; if the item is incatted it shifts automatically to
        the Survey or Demand cart within the MO / WED Inventory module for Ship Staff to raise the
        survey or demand.</li>
  </ol>
  <h6 class="fw-bold mb-1">Good to know</h6>
  <ul class="mb-0">
    <li><strong>Parent Inventory</strong> — which shore inventory the item belongs to: ILMS (MO) or WLMS (WED).</li>
    <li><strong>Pattern Number</strong> shown here is the temporary SWMM-generated one until you fix it or the item is incatted.</li>
    <li><strong>Category</strong> — P = Permanent, R = Returnable, C = Consumable.</li>
  </ul>
`;

@Component({
  selector: "app-obs-iif-list",
  standalone: true,
  imports: [
    ReactiveFormsModule,
    DataGrid,
    ModalComponent,
    SelectInput,
    InputField,
    ExportToolbar,
    ToolbarSearch,
    IconComponent,
    HelpGuidance,
  ],
  templateUrl: "./iif-list.html",
  styleUrl: "./iif-list.css",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IifList implements OnInit {
  private readonly api = inject(ObsApiService);
  private readonly fb = inject(FormBuilder);
  private readonly notifications = inject(NotificationService);
  private readonly exportService = inject(ReportExportService);

  readonly helpHtml = HELP_HTML;
  readonly parentInventoryOptions = PARENT_INVENTORY_OPTIONS;
  readonly categoryFilterOptions = CATEGORY_FILTER_OPTIONS;
  readonly entries = signal<IifEntry[]>([]);
  readonly selectedRows = signal<IifEntry[]>([]);
  readonly cartModalOpen = signal(false);
  readonly editEntry = signal<IifEntry | null>(null);
  readonly saving = signal(false);
  readonly exportBusy = signal<ExportKind | null>(null);
  readonly searchText = signal("");
  readonly criticalOnly = signal(false);
  readonly categoryFilters = signal<Record<SpareCategoryFilter, boolean>>({
    PERMANENT: true,
    RETURNABLE: true,
    CONSUMABLE: true,
  });

  readonly columnDefs: ColDef[] = [
    { field: "parentInventory", headerName: "Parent Inventory", width: 140 },
    {
      headerName: "INcatting Status",
      width: 140,
      valueGetter: () => "No",
    },
    { field: "patternNumber", headerName: "Pattern Number", flex: 1 },
    { field: "description", headerName: "Spare Description", flex: 1.2 },
    { field: "quantity", headerName: "Qty", width: 90 },
    { field: "category", headerName: "Category", width: 100 },
    { field: "equipmentClass", headerName: "Equipment Class", flex: 1 },
    {
      field: "critical",
      headerName: "Critical",
      width: 100,
      valueGetter: (p) => ((p.data as IifEntry).critical ? "YES" : "NO"),
    },
    { field: "authority", headerName: "Authority", width: 110 },
    {
      headerName: "Action",
      width: 150,
      sortable: false,
      valueGetter: () => "Click row to edit",
    },
  ];

  readonly printColumns: PrintColumn[] = [
    { header: "Parent Inventory", field: "parentInventory" },
    { header: "INcatting Status", field: "incattingStatus", format: () => "No" },
    { header: "Pattern Number", field: "patternNumber" },
    { header: "Spare Description", field: "description" },
    { header: "Qty", field: "quantity" },
    { header: "Category", field: "category" },
    { header: "Equipment Class", field: "equipmentClass" },
    { header: "Critical", field: "critical", format: (v) => (v ? "YES" : "NO") },
    { header: "Authority", field: "authority" },
  ];

  readonly filteredEntries = computed(() => {
    const critical = this.criticalOnly();
    const categories = this.categoryFilters();
    const query = this.searchText().trim().toLowerCase();
    return this.entries().filter((entry) => {
      if (critical && !entry.critical) return false;
      const categoryKey = entry.category?.toUpperCase() as SpareCategoryFilter | undefined;
      if (categoryKey && categoryKey in categories && !categories[categoryKey]) return false;
      if (
        query &&
        ![entry.patternNumber, entry.description, entry.authority, entry.equipmentClass].some((value) =>
          (value ?? "").toLowerCase().includes(query),
        )
      ) {
        return false;
      }
      return true;
    });
  });

  readonly cartForm = this.fb.nonNullable.group({
    parentInventory: ["ILMS" as ParentInventory, Validators.required],
  });

  readonly patternForm = this.fb.nonNullable.group({
    patternNumber: ["", Validators.required],
  });

  ngOnInit(): void {
    void this.load();
  }

  private async load(): Promise<void> {
    this.entries.set(await firstValueFrom(this.api.getIifList()));
  }

  toggleCategory(key: SpareCategoryFilter): void {
    this.categoryFilters.update((current) => ({ ...current, [key]: !current[key] }));
  }

  onExport(kind: ExportKind): void {
    const rows = this.filteredEntries() as unknown as Record<string, unknown>[];
    if (kind === "excel") {
      this.exportService.downloadCsv(this.printColumns, rows, "iif-list.csv");
      return;
    }
    this.exportService.printRows("IIF Item List", this.printColumns, rows);
  }

  copyRows(): void {
    void this.exportService.copyRows(this.printColumns, this.filteredEntries() as unknown as Record<string, unknown>[]);
    this.notifications.success("Copied to clipboard.");
  }

  onSelectionChanged(rows: RowData[]): void {
    this.selectedRows.set(rows as unknown as IifEntry[]);
  }

  onRowClicked(row: RowData): void {
    const entry = row as unknown as IifEntry;
    this.editEntry.set(entry);
    this.patternForm.reset({ patternNumber: "" });
  }

  closeEditModal(): void {
    this.editEntry.set(null);
  }

  async verifyAndUpdate(): Promise<void> {
    const entry = this.editEntry();
    if (!entry || this.patternForm.invalid) {
      this.patternForm.markAllAsTouched();
      return;
    }
    this.saving.set(true);
    try {
      const patternNumber = this.patternForm.getRawValue().patternNumber;
      const result = await firstValueFrom(this.api.verifyPatternNumber(entry.id, patternNumber));
      if (!result.matched) {
        this.notifications.error("Pattern number did not match ILMS/WLMS. Please check and try again.");
        return;
      }
      await firstValueFrom(this.api.updateIifPatternNumber(entry.id, patternNumber));
      this.closeEditModal();
      void this.load();
    } finally {
      this.saving.set(false);
    }
  }

  openCartModal(): void {
    if (!this.selectedRows().length) return;
    this.cartModalOpen.set(true);
  }

  closeCartModal(): void {
    this.cartModalOpen.set(false);
  }

  async confirmSendToCart(): Promise<void> {
    this.saving.set(true);
    try {
      const raw = this.cartForm.getRawValue();
      await firstValueFrom(
        this.api.sendIifToCart({ ids: this.selectedRows().map((r) => r.id), cartType: "Survey", ...raw }),
      );
      this.closeCartModal();
      void this.load();
    } finally {
      this.saving.set(false);
    }
  }
}
