# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionStationMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Action Station (Master)",
                "verbose_name_plural": "Action Stations (Master)",
                "db_table": "crewmanage_actionstationmaster",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AddressDetails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("address_permanent", models.TextField(blank=True, null=True)),
                (
                    "country_permanent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email_permanent",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "number_permanent",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "line1_other",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "line2_other",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "district_other",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city_other", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state_other",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "country_other",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pincode_other",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email_other",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_other",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "crewmanage_addressdetails",
            },
        ),
        migrations.CreateModel(
            name="CivilianOfficial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_snapshot", models.CharField(blank=True, max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Barber", "Barber"),
                            ("CIV Bearer", "CIV Bearer"),
                            ("MES Boy", "MES Boy"),
                            ("Canteen Manager", "Canteen Manager"),
                            ("NAAFI Staff", "NAAFI Staff"),
                            ("Dhobi", "Dhobi"),
                            ("Cook (Civ)", "Cook (Civ)"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, help_text="Aadhar / Emp No.", max_length=50
                    ),
                ),
                ("contact", models.CharField(blank=True, max_length=20)),
                ("remarks", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("person_type", models.CharField(blank=True, max_length=50)),
                ("rank_snapshot", models.CharField(blank=True, max_length=80)),
                ("pno_snapshot", models.CharField(blank=True, max_length=50)),
                ("dept_snapshot", models.CharField(blank=True, max_length=100)),
                ("desig_snapshot", models.CharField(blank=True, max_length=150)),
                ("service_no", models.CharField(blank=True, max_length=100)),
                ("fleet", models.CharField(blank=True, max_length=200)),
                ("ship", models.CharField(blank=True, max_length=200)),
                ("cid", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Civilian Official",
                "verbose_name_plural": "Civilian Officials",
                "db_table": "crewmanage_civilianofficial",
                "ordering": ["role", "name_snapshot"],
            },
        ),
        migrations.CreateModel(
            name="CruisingStationMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cruising Station (Master)",
                "verbose_name_plural": "Cruising Stations (Master)",
                "db_table": "crewmanage_cruisingstationmaster",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DefenceStationMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Defence Station (Master)",
                "verbose_name_plural": "Defence Stations (Master)",
                "db_table": "crewmanage_defencestationmaster",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyStationMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Emergency Station (Master)",
                "verbose_name_plural": "Emergency Stations (Master)",
                "db_table": "crewmanage_emergencystationmaster",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GXForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gx_no", models.CharField(max_length=50)),
                ("gx_date", models.DateTimeField()),
                (
                    "occurrence",
                    models.CharField(
                        choices=[("AM", "AM"), ("PM", "PM")], max_length=2
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="gx_forms/"),
                ),
                ("leave_id", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "crewmanage_gxform",
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personal_number", models.CharField(max_length=50)),
                ("rank", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("designation", models.CharField(blank=True, max_length=100)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[("On Leave", "On Leave"), ("Ty Duty", "Ty Duty")],
                        max_length=20,
                    ),
                ),
                ("has_prefix", models.BooleanField(default=False)),
                ("prefix_start_date", models.DateField(blank=True, null=True)),
                ("prefix_start_time", models.TimeField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("suffix_completion_date", models.DateField(blank=True, null=True)),
                ("suffix_completion_time", models.TimeField(blank=True, null=True)),
                ("reporting_date", models.DateField(blank=True, null=True)),
                ("reporting_time", models.TimeField(blank=True, null=True)),
                ("no_of_days", models.PositiveIntegerField(default=0)),
                ("station", models.CharField(blank=True, max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("remark", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="leave_attachments/"
                    ),
                ),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("approved_rejected_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leave Application",
                "verbose_name_plural": "Leave Applications",
                "db_table": "crewmanage_leaveapplication",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApprovalHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("approved_by_id", models.IntegerField()),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Submitted", "Submitted"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_datetime", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "crewmanage_leave_approval_history",
                "ordering": ["-action_datetime"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApprovalWorkflow",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reg", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "reg_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("do", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "do_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("dhod", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dhod_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("hod", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "hod_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("co", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "co_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("gx", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gx_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("return_remarks", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "crewmanage_leave_approval_workflow",
            },
        ),
        migrations.CreateModel(
            name="LeaveDetails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("type_of_leave", models.CharField(max_length=100)),
                ("category_of_leave", models.CharField(max_length=100)),
                ("commencement_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("no_of_days", models.PositiveIntegerField()),
                ("leave_year", models.CharField(blank=True, max_length=4, null=True)),
                ("prefix_date", models.DateField(blank=True, null=True)),
                ("prefix_days", models.PositiveIntegerField(default=0)),
                ("suffix_date", models.DateField(blank=True, null=True)),
                ("suffix_days", models.PositiveIntegerField(default=0)),
                ("leave_station", models.TextField(blank=True, null=True)),
                ("travel_start_date", models.DateField(blank=True, null=True)),
                ("tt_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "station_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "railway_station",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("lmc_date", models.DateField(blank=True, null=True)),
                (
                    "medical_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "with_without_passage",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "passage_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ration_type", models.CharField(blank=True, max_length=50, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Returned", "Returned"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "crewmanage_leavedetails",
            },
        ),
        migrations.CreateModel(
            name="LtcDays",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "crewmanage_ltcdays",
            },
        ),
        migrations.CreateModel(
            name="MedicalCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "crewmanage_medicalcategory",
            },
        ),
        migrations.CreateModel(
            name="ModeOfTravel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "crewmanage_modeoftravel",
            },
        ),
        migrations.CreateModel(
            name="PassageType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "crewmanage_passagetype",
            },
        ),
        migrations.CreateModel(
            name="PersonnelAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pno", models.CharField(db_index=True, max_length=50)),
                ("name_snapshot", models.CharField(blank=True, max_length=200)),
                ("rank_snapshot", models.CharField(blank=True, max_length=80)),
                ("dept_snapshot", models.CharField(blank=True, max_length=100)),
                ("w3", models.CharField(blank=True, max_length=50)),
                ("w2", models.CharField(blank=True, max_length=50)),
                ("action", models.CharField(blank=True, max_length=100)),
                ("defence", models.CharField(blank=True, max_length=100)),
                ("cruising", models.CharField(blank=True, max_length=100)),
                ("shelter", models.CharField(blank=True, max_length=100)),
                ("emergency", models.CharField(blank=True, max_length=100)),
                ("lr", models.CharField(blank=True, max_length=50)),
                ("mess", models.CharField(blank=True, max_length=50)),
                ("ssd", models.CharField(blank=True, max_length=50)),
                ("mess_stn", models.CharField(blank=True, max_length=50)),
                ("section", models.CharField(blank=True, max_length=50)),
                ("remarks", models.TextField(blank=True)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Personnel Assignment",
                "verbose_name_plural": "Personnel Assignments",
                "db_table": "crewmanage_personnelassignment",
                "ordering": ["dept_snapshot", "rank_snapshot"],
            },
        ),
        migrations.CreateModel(
            name="PersonnelStatusLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rank", models.CharField(max_length=50, null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("personnel_number", models.CharField(max_length=50, null=True)),
                ("department", models.CharField(max_length=50, null=True)),
                ("designation", models.CharField(max_length=50, null=True)),
                ("status", models.CharField(max_length=50)),
                ("log_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "crewmanage_personnelstatuslog",
            },
        ),
        migrations.CreateModel(
            name="PlaceOfTyDuty",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "crewmanage_placeoftyduty",
            },
        ),
        migrations.CreateModel(
            name="Railway",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "crewmanage_railway",
            },
        ),
        migrations.CreateModel(
            name="RationType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "crewmanage_rationtype",
            },
        ),
        migrations.CreateModel(
            name="Sailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("area", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "co_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Commanding Officer"
                    ),
                ),
                (
                    "xo_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Executive Officer"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sailing",
                "verbose_name_plural": "Sailings",
                "db_table": "crewmanage_sailing",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SailingPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank_snapshot", models.CharField(blank=True, max_length=80)),
                ("name_snapshot", models.CharField(max_length=200)),
                ("pno_snapshot", models.CharField(max_length=50)),
                ("dept_snapshot", models.CharField(blank=True, max_length=100)),
                ("desig_snapshot", models.CharField(blank=True, max_length=150)),
                ("watch_station", models.CharField(blank=True, max_length=150)),
                ("action_station", models.CharField(blank=True, max_length=150)),
                (
                    "status_override",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("On Leave", "On Leave"),
                            ("Ty Duty", "Ty Duty"),
                        ],
                        default="Present",
                        max_length=20,
                    ),
                ),
                ("person_type", models.CharField(blank=True, max_length=50)),
                ("role", models.CharField(blank=True, max_length=150)),
                ("service_no", models.CharField(blank=True, max_length=100)),
                ("fleet", models.CharField(blank=True, max_length=200)),
                ("ship", models.CharField(blank=True, max_length=200)),
                ("cid", models.CharField(blank=True, max_length=100)),
                ("contact", models.CharField(blank=True, max_length=50)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Sailing Personnel",
                "verbose_name_plural": "Sailing Personnel",
                "db_table": "crewmanage_sailingpersonnel",
                "ordering": ["dept_snapshot", "rank_snapshot"],
            },
        ),
        migrations.CreateModel(
            name="SailorRankClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank_name", models.CharField(max_length=100, unique=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[("Senior", "Senior"), ("Junior", "Junior")],
                        default="Junior",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Junior/Senior Sailor Classification",
                "verbose_name_plural": "Junior/Senior Sailor Classifications",
                "db_table": "crewmanage_sailorrankclassification",
                "ordering": ["rank_name"],
            },
        ),
        migrations.CreateModel(
            name="ShelterStationMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shelter Station (Master)",
                "verbose_name_plural": "Shelter Stations (Master)",
                "db_table": "crewmanage_shelterstationmaster",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemporaryDuty",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("temp_duty_type", models.CharField(max_length=100)),
                ("commencement_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("no_of_days", models.PositiveIntegerField()),
                ("tt_days", models.PositiveIntegerField(blank=True, null=True)),
                ("joining_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "station_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("gx_unit", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "place_of_duty",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "with_without_passage",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "passage_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ration_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "authority_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("authority_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "file_upload",
                    models.FileField(blank=True, null=True, upload_to="ty_duty_files/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Returned", "Returned"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "crewmanage_temporaryduty",
            },
        ),
        migrations.CreateModel(
            name="TemporaryDutyApprovalHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Submitted", "Submitted"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USER", "User"),
                            ("REG", "Registrar"),
                            ("DO", "District Officer"),
                            ("DHOD", "Deputy Head of Department"),
                            ("HOD", "Head of Department"),
                            ("CO", "Controlling Officer"),
                            ("GX", "Government Executive"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "crewmanage_temporarydutyapprovalhistory",
            },
        ),
        migrations.CreateModel(
            name="TemporaryDutyApprovalWorkflow",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reg", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "reg_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("do", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "do_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("dhod", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dhod_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("hod", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "hod_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("co", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "co_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("gx", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gx_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Forwarded", "Forwarded"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("return_remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "ty_duty_approval_workflow",
            },
        ),
        migrations.CreateModel(
            name="TypeOfLeave",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("leave_numbers", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "crewmanage_typeofleave",
            },
        ),
        migrations.CreateModel(
            name="TypeOfTempDuty",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "crewmanage_typeoftempduty",
            },
        ),
    ]
