# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crew_manage", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="civilianofficial",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_applications_submitted",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="approved_rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_applications_actioned",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="leavedetails",
            name="address_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crew_manage.addressdetails",
            ),
        ),
        migrations.AddField(
            model_name="leaveapprovalworkflow",
            name="leave_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_workflow",
                to="crew_manage.leavedetails",
            ),
        ),
        migrations.AddField(
            model_name="leaveapprovalhistory",
            name="leave_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_history",
                to="crew_manage.leavedetails",
            ),
        ),
        migrations.AddField(
            model_name="personnelstatuslog",
            name="leave_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="crew_manage.leaveapplication",
            ),
        ),
        migrations.AddField(
            model_name="sailing",
            name="civilians",
            field=models.ManyToManyField(
                blank=True,
                db_table="crewmanage_sailing_civilians",
                related_name="sailings",
                to="crew_manage.civilianofficial",
            ),
        ),
        migrations.AddField(
            model_name="sailing",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="personnelassignment",
            name="sailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="crew_manage.sailing",
            ),
        ),
        migrations.AddField(
            model_name="sailingpersonnel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sailing_personnel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sailingpersonnel",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sailing_entries",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="sailingpersonnel",
            name="sailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personnel",
                to="crew_manage.sailing",
            ),
        ),
        migrations.AddField(
            model_name="temporaryduty",
            name="address_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crew_manage.addressdetails",
            ),
        ),
        migrations.AddField(
            model_name="temporarydutyapprovalhistory",
            name="duty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_history",
                to="crew_manage.temporaryduty",
            ),
        ),
        migrations.AddField(
            model_name="temporarydutyapprovalworkflow",
            name="duty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_workflow",
                to="crew_manage.temporaryduty",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personnelassignment",
            unique_together={("sailing", "pno")},
        ),
        migrations.AlterUniqueTogether(
            name="sailingpersonnel",
            unique_together={("sailing", "pno_snapshot")},
        ),
    ]
