# Generated by Django 5.2.15 on 2026-08-10 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew_manage", "0002_initial"),
        ("users", "0002_alter_loginregistrationimage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionstationmaster",
            options={
                "ordering": ("name",),
                "verbose_name": "Action Station (Master)",
                "verbose_name_plural": "Action Stations (Master)",
            },
        ),
        migrations.AlterModelOptions(
            name="civilianofficial",
            options={
                "ordering": ("role", "name_snapshot"),
                "verbose_name": "Civilian Official",
                "verbose_name_plural": "Civilian Officials",
            },
        ),
        migrations.AlterModelOptions(
            name="cruisingstationmaster",
            options={
                "ordering": ("name",),
                "verbose_name": "Cruising Station (Master)",
                "verbose_name_plural": "Cruising Stations (Master)",
            },
        ),
        migrations.AlterModelOptions(
            name="defencestationmaster",
            options={
                "ordering": ("name",),
                "verbose_name": "Defence Station (Master)",
                "verbose_name_plural": "Defence Stations (Master)",
            },
        ),
        migrations.AlterModelOptions(
            name="emergencystationmaster",
            options={
                "ordering": ("name",),
                "verbose_name": "Emergency Station (Master)",
                "verbose_name_plural": "Emergency Stations (Master)",
            },
        ),
        migrations.AlterModelOptions(
            name="leaveapplication",
            options={
                "ordering": ("-applied_at",),
                "verbose_name": "Leave Application",
                "verbose_name_plural": "Leave Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="leaveapprovalhistory",
            options={"ordering": ("-action_datetime",)},
        ),
        migrations.AlterModelOptions(
            name="personnelassignment",
            options={
                "ordering": ("dept_snapshot", "rank_snapshot"),
                "verbose_name": "Personnel Assignment",
                "verbose_name_plural": "Personnel Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="sailing",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Sailing",
                "verbose_name_plural": "Sailings",
            },
        ),
        migrations.AlterModelOptions(
            name="sailingpersonnel",
            options={
                "ordering": ("dept_snapshot", "rank_snapshot"),
                "verbose_name": "Sailing Personnel",
                "verbose_name_plural": "Sailing Personnel",
            },
        ),
        migrations.AlterModelOptions(
            name="sailorrankclassification",
            options={
                "ordering": ("rank_name",),
                "verbose_name": "Junior/Senior Sailor Classification",
                "verbose_name_plural": "Junior/Senior Sailor Classifications",
            },
        ),
        migrations.AlterModelOptions(
            name="shelterstationmaster",
            options={
                "ordering": ("name",),
                "verbose_name": "Shelter Station (Master)",
                "verbose_name_plural": "Shelter Stations (Master)",
            },
        ),
        migrations.AlterField(
            model_name="actionstationmaster",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="civilianofficial",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cruisingstationmaster",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="emergencystationmaster",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="gxform",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="applied_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_applications_submitted",
                to="users.customuserprofile",
            ),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="leaveapprovalhistory",
            name="action_taken",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Forwarded", "Forwarded"),
                    ("Returned", "Returned"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personnelassignment",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sailing",
            name="civilians",
            field=models.ManyToManyField(
                blank=True, related_name="sailings", to="crew_manage.civilianofficial"
            ),
        ),
        migrations.AlterField(
            model_name="sailing",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sailing",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sailingpersonnel",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sailorrankclassification",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="shelterstationmaster",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="temporarydutyapprovalhistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Forwarded", "Forwarded"),
                    ("Returned", "Returned"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="passagetype",
            table=None,
        ),
        migrations.AlterModelTable(
            name="personnelstatuslog",
            table=None,
        ),
        migrations.AlterModelTable(
            name="shelterstationmaster",
            table=None,
        ),
    ]
