# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementFuelsondingFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tank_type", models.CharField(blank=True, max_length=255)),
                ("tank_name", models.CharField(blank=True, max_length=255)),
                ("mm", models.FloatField()),
                ("volume", models.FloatField()),
                ("tone", models.FloatField(blank=True, null=True)),
                ("field_10mm", models.FloatField(blank=True, null=True)),
                ("field_20mm", models.FloatField(blank=True, null=True)),
                ("field_30mm", models.FloatField(blank=True, null=True)),
                ("field_40mm", models.FloatField(blank=True, null=True)),
                ("field_50mm", models.FloatField(blank=True, null=True)),
                ("field_60mm", models.FloatField(blank=True, null=True)),
                ("field_70mm", models.FloatField(blank=True, null=True)),
                ("field_80mm", models.FloatField(blank=True, null=True)),
                ("field_90mm", models.FloatField(blank=True, null=True)),
                ("field_100per", models.BooleanField(blank=True, null=True)),
                ("field_95per", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Measurement",
                "verbose_name_plural": "Measurements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TankFluidUnit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fluid_unit", models.CharField(max_length=255)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TankOil",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("oil_type", models.CharField(max_length=255)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="FluidType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fluid_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.customuserprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fluid",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fluid", models.CharField(blank=True, max_length=255)),
                ("measuring_unit", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "fluid_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fluids",
                        to="tank.fluidtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hierarchyforchart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_type", models.CharField(default="co", max_length=50)),
                ("division_name", models.CharField(blank=True, max_length=255)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("rank", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("personal_number", models.CharField(max_length=50)),
                ("photo", models.ImageField(upload_to="masters/hierarchy/")),
                ("is_commander_officer", models.BooleanField(default=False)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="tank.hierarchyforchart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TankCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tank_category", models.CharField(blank=True, max_length=255)),
                ("manual_name", models.CharField(blank=True, max_length=100)),
                (
                    "graph_no",
                    models.IntegerField(
                        blank=True,
                        help_text="Order in which this graph appears (e.g. 1, 2, 3...)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "fluid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tank.fluid",
                    ),
                ),
            ],
            options={
                "ordering": ["graph_no", "tank_category"],
            },
        ),
        migrations.CreateModel(
            name="FuellingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuelling_at", models.CharField(blank=True, max_length=100)),
                ("fuelling_start_date", models.DateField(blank=True, null=True)),
                ("fuelling_start_time", models.TimeField(blank=True, null=True)),
                ("fuelling_stop_date", models.DateField(blank=True, null=True)),
                ("fuelling_stop_time", models.TimeField(blank=True, null=True)),
                ("received_at_station", models.CharField(blank=True, max_length=255)),
                ("received_from_ship", models.CharField(blank=True, max_length=255)),
                ("fluid_in_tank", models.CharField(blank=True, max_length=100)),
                ("received_through", models.CharField(blank=True, max_length=100)),
                (
                    "fuel_received",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_fuel_received",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "fuelling_rate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("is_fuelling_completed", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                (
                    "voucher_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="fuelling_vouchers/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "tank_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tank_category_fuelling_details",
                        to="tank.tankcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FluidInTank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fluid_name", models.CharField(max_length=255)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tank_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fluids",
                        to="tank.tankcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TankFuelSounding",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mm", models.FloatField()),
                ("volume", models.FloatField()),
                ("tone", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tank.tankcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TankLocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.customuserprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TankRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("manual_name", models.CharField(blank=True, max_length=100)),
                (
                    "mm_measurement",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "volume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("reading_time", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tank.tanklocation",
                    ),
                ),
                (
                    "oil_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tank.tankoil",
                    ),
                ),
                (
                    "tank_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tank.tankcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TankTypeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tank_type", models.CharField(blank=True, default="", max_length=100)),
                (
                    "tank_subtype",
                    models.CharField(blank=True, default="storage", max_length=20),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Capacity of the tank (usually in Tonnes)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fluid_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tank.fluidtype",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tank.tanklocation",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="tank.tankcategory",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tank.tankfluidunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tank Type Detail",
                "verbose_name_plural": "Tank Type Details",
                "ordering": ["tank__tank_category"],
            },
        ),
        migrations.CreateModel(
            name="TankSoundingMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mm_level", models.FloatField()),
                ("volume", models.FloatField()),
                (
                    "percentage_flag",
                    models.IntegerField(
                        blank=True, choices=[(95, "95%"), (100, "100%")], null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "tank_category_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sounding_master",
                        to="tank.tanktypedetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tank Sounding Master",
                "verbose_name_plural": "Tank Sounding Masters",
                "ordering": ["tank_category_detail", "mm_level"],
                "unique_together": {("tank_category_detail", "mm_level")},
            },
        ),
        migrations.CreateModel(
            name="TankSoundingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mm_measurement", models.FloatField()),
                ("tonnes", models.FloatField(blank=True, null=True)),
                ("reading_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tank_category_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sounding_data",
                        to="tank.tanktypedetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tank Sounding Data",
                "verbose_name_plural": "Tank Sounding Data",
                "ordering": ["-reading_time"],
                "indexes": [
                    models.Index(
                        fields=["tank_category_detail", "-reading_time"],
                        name="tank_tankso_tank_ca_c7dbe8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SoundingDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_sounding_mm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "start_ras_tons",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "limiting_sounding_mm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "during_sounding_mm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "during_ras_tons",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "received_fuel_tons",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "capacity_tons",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "short_tons",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False,
                        help_text="True if 'Fueling Completed' was clicked",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ras_monitor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ras_monitor_sounding_drafts",
                        to="tank.fuellingdetails",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sounding_drafts",
                        to="tank.tanktypedetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sounding Draft",
                "verbose_name_plural": "Sounding Drafts",
                "unique_together": {("ras_monitor_id", "tank")},
            },
        ),
    ]
