title = "SWMM Ship Gitleaks Configuration"

[allowlist]
description = "Allowed paths"

paths = [
  '''frontend/package-lock.json''',
  '''frontend/yarn.lock''',
  '''backend/backend_drf/poetry.lock'''
]
