# Generated by Django 5.2.15 on 2026-08-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddHotwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holiday_or_working_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOLIDAY", "Holiday"),
                            ("WORKING_DAY", "Working Day"),
                        ],
                        default="WORKING_DAY",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "hotwork_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_of_hotwork", models.DateField(db_index=True)),
                ("sentries_required", models.BooleanField(default=True)),
                (
                    "previous_hotwork_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("location_of_hotwork", models.CharField(max_length=200)),
                (
                    "type_of_hotwork",
                    models.CharField(
                        choices=[
                            ("CUTTING", "Cutting"),
                            ("WELDING", "Welding"),
                            ("CUTTING_WELDING", "Cutting + Welding"),
                            ("GRINDING", "Grinding"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "departmental_officer",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "all_adjacent_compartments",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sentry_names", models.TextField(blank=True, null=True)),
                ("dl_number", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "supervision_welder_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "manager_of_concern_center",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("night_work", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending_incharge", "Not Started"),
                            ("pending_dyhod", "Initiated"),
                            ("pending_first_hod", "Not Started"),
                            ("pending_hods", "Initiated"),
                            ("pending_ood", "Initiated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending_incharge",
                        max_length=25,
                    ),
                ),
                ("incharge_approved", models.BooleanField(default=False)),
                ("incharge_approved_at", models.DateTimeField(blank=True, null=True)),
                ("dyhod_approved", models.BooleanField(default=False)),
                ("dyhod_approved_at", models.DateTimeField(blank=True, null=True)),
                ("all_hods_approved", models.BooleanField(default=False)),
                ("ood_approved", models.BooleanField(default=False)),
                ("ood_approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_started", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("is_paused", models.BooleanField(default=False)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("pause_reason", models.TextField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completion_remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Hotwork_addhotwork",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HotworkHODApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "earthing_gts",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "fire_sensor_ops",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPS", "Operational"),
                            ("NON_OPS", "Non Operational"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "fire_sensor_non_ops_remarks",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "flood_sensor_ops",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPS", "Operational"),
                            ("NON_OPS", "Non Operational"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "flood_sensor_non_ops_remarks",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "supply_point",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "iccp_off",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "fire_extinguisher",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "fire_hose",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "firemain_pressure",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "free_lagging",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "sentry_knowledge",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "Hotwork_hotworkhodapproval",
            },
        ),
        migrations.CreateModel(
            name="HotworkProgressActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("paused", "Paused"),
                            ("resumed", "Resumed"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Hotwork_hotworkprogressactivity",
                "ordering": ["-performed_at"],
            },
        ),
    ]
