# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotwork", "0001_initial"),
        ("master", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addhotwork",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_hotworks",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="addhotwork",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_hotworks",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="addhotwork",
            name="dyhod_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dyhod_approved_hotworks",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="addhotwork",
            name="hotwork_incharge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hotwork_incharge_hotworks",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="addhotwork",
            name="incharge_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incharge_approved_hotworks",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="addhotwork",
            name="officer_of_the_day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ood_assigned_hotworks",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="addhotwork",
            name="ood_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ood_approved_hotworks",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="addhotwork",
            name="paused_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paused_hotworks",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="addhotwork",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="started_hotworks",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="addhotwork",
            name="sub_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.subdepartment",
            ),
        ),
        migrations.AddField(
            model_name="hotworkhodapproval",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="hotworkhodapproval",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="master.department"
            ),
        ),
        migrations.AddField(
            model_name="hotworkhodapproval",
            name="hotwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hod_approvals",
                to="hotwork.addhotwork",
            ),
        ),
        migrations.AddField(
            model_name="hotworkprogressactivity",
            name="hotwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_activities",
                to="hotwork.addhotwork",
            ),
        ),
        migrations.AddField(
            model_name="hotworkprogressactivity",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.customuserprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="hotworkhodapproval",
            constraint=models.UniqueConstraint(
                fields=("hotwork", "department"), name="unique_hotwork_department"
            ),
        ),
    ]
