# Generated by Django 5.2.15 on 2026-08-10 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotwork", "0002_initial"),
        ("master", "0003_alter_chmastersymptoms_department_and_more"),
        ("users", "0002_alter_loginregistrationimage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addhotwork",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="hotworkprogressactivity",
            options={"ordering": ("-performed_at",)},
        ),
        migrations.RemoveConstraint(
            model_name="hotworkhodapproval",
            name="unique_hotwork_department",
        ),
        migrations.RemoveField(
            model_name="addhotwork",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="addhotwork",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending_incharge", "Not Started"),
                    ("pending_dyhod", "Initiated"),
                    ("pending_first_hod", "Not Started"),
                    ("pending_hods", "Initiated"),
                    ("pending_ood", "Initiated"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending_incharge",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="addhotwork",
            name="hotwork_incharge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hotwork_incharge",
                to="users.customuserprofile",
            ),
        ),
        migrations.AlterField(
            model_name="addhotwork",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="addhotwork",
            name="officer_of_the_day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="officer_of_the_day",
                to="users.customuserprofile",
            ),
        ),
        migrations.AlterField(
            model_name="addhotwork",
            name="type_of_hotwork",
            field=models.CharField(
                choices=[
                    ("CUTTING", "Cutting"),
                    ("WELDING", "Welding"),
                    ("CUTTING_WELDING", "Cutting + Welding"),
                    ("GRINDING", "Grinding"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="hotworkhodapproval",
            name="earthing_gts",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="hotworkhodapproval",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="hotworkprogressactivity",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="hotworkprogressactivity",
            name="performed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="hotworkprogressactivity",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.customuserprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hotworkhodapproval",
            unique_together={("hotwork", "department")},
        ),
    ]
