# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "customer_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mother_depot",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("addressee", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_line3",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("pin_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "allowance_annual_rs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("date_introduced", models.DateField(blank=True, null=True)),
                ("date_closed", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "admin_authority",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "station_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("added_by", models.CharField(blank=True, max_length=50, null=True)),
                ("closed_by", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "ILMS_customer",
            },
        ),
        migrations.CreateModel(
            name="CustomerEquipmentLine",
            fields=[
                (
                    "customer_eqpt_line_ser",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "eqpt_serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("position_specific_yn", models.BooleanField(blank=True, null=True)),
                (
                    "fitment_port_stbd",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("rotation_rl", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "eqpt_nomenclature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "generic_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("eqpt_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "manufacturer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "parent_eqpt",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_onboard",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_fit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("added_by", models.CharField(blank=True, max_length=50, null=True)),
                ("datetime_added", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.CharField(blank=True, max_length=50, null=True)),
                ("datetime_closed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ILMS_customerequipmentline",
            },
        ),
        migrations.CreateModel(
            name="DartMOSpare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_date", models.DateField(auto_now_add=True, null=True)),
                ("modified_date", models.DateField(auto_now_add=True, null=True)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ILMS_dartmosspare",
            },
        ),
        migrations.CreateModel(
            name="DemandDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "in_progress_status",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "demand_number",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_demand", models.BooleanField(default=False)),
                ("is_sync", models.BooleanField(default=False)),
                ("is_hod", models.BooleanField(default=False)),
                ("is_hod_approval", models.BooleanField(default=False)),
                ("mo_status", models.CharField(default="Pending", max_length=200)),
            ],
            options={
                "db_table": "ILMS_modemanddetails",
            },
        ),
        migrations.CreateModel(
            name="IIF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_sync", models.BooleanField(default=False)),
                ("sync_response", models.BooleanField(default=False)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ILMS_iif",
            },
        ),
        migrations.CreateModel(
            name="IssuedDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abc_ved_year",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "station_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("no_of_issues", models.IntegerField(blank=True, null=True)),
                ("qty_issued", models.IntegerField(blank=True, null=True)),
                (
                    "issued_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "db_table": "ILMS_issueddetails",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "item_code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "section_head",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("item_desc", models.TextField(blank=True, null=True)),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("item_deno", models.CharField(blank=True, max_length=50, null=True)),
                ("months_shelf_life", models.IntegerField(blank=True, null=True)),
                (
                    "crp_category",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "ved_category",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "abc_category",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("datetime_approved", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "review_sub_section_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("incat_yn", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ILMS_iteam",
            },
        ),
        migrations.CreateModel(
            name="ItemExtra",
            fields=[
                (
                    "item_code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("item_desc", models.TextField(blank=True, null=True)),
                (
                    "equipment_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "PERMANENT"),
                            ("RETURNABLE", "RETURNABLE"),
                            ("CONSUMABLE", "CONSUMABLE"),
                        ],
                        default="PERMANENT",
                        max_length=30,
                    ),
                ),
                ("critical", models.BooleanField(default=False)),
                (
                    "ved_category",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "abc_category",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "crp_category",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("datetime_approved", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.CharField(blank=True, max_length=50, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="default.png", null=True, upload_to="items/"
                    ),
                ),
            ],
            options={
                "db_table": "ILMS_item_extra",
            },
        ),
        migrations.CreateModel(
            name="ItemIssued",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demand_no", models.CharField(blank=True, max_length=50, null=True)),
                ("sh_no", models.CharField(blank=True, max_length=50, null=True)),
                ("qty", models.IntegerField(blank=True, null=True)),
                (
                    "price_rs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("datetime_obd", models.DateTimeField(blank=True, null=True)),
                ("issue_datetime", models.DateTimeField(blank=True, null=True)),
                ("issued_by", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "station_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("issued_type", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "ILMS_itemissued",
            },
        ),
        migrations.CreateModel(
            name="ItemLine",
            fields=[
                (
                    "station_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sh_no", models.CharField(blank=True, max_length=50, null=True)),
                ("qty_war_reserve", models.IntegerField(blank=True, null=True)),
                ("qty_msl", models.IntegerField(blank=True, null=True)),
                ("qty_usl", models.IntegerField(blank=True, null=True)),
                ("qty_acl", models.IntegerField(blank=True, null=True)),
                ("days_lt_proc", models.IntegerField(blank=True, null=True)),
                ("datetime_added", models.DateTimeField(blank=True, null=True)),
                ("datetime_closed", models.DateTimeField(blank=True, null=True)),
                (
                    "item_line_serial",
                    models.AutoField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "ILMS_itemline",
            },
        ),
        migrations.CreateModel(
            name="ItemVendor",
            fields=[
                ("active_yn", models.BooleanField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                (
                    "certification_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "certification_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pac_ref", models.CharField(blank=True, max_length=50, null=True)),
                ("date_pac", models.DateField(blank=True, null=True)),
                ("datetime_approved", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.CharField(blank=True, max_length=50, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("datetime_till", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "station_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("datetime_closed", models.DateTimeField(blank=True, null=True)),
                (
                    "item_vendor_serial_no",
                    models.AutoField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "ILMS_itemvendor",
            },
        ),
        migrations.CreateModel(
            name="MOItemEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemcode", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "eask_item_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("eask_type", models.CharField(blank=True, max_length=50, null=True)),
                ("qty_constituent", models.IntegerField(blank=True, null=True)),
                ("qty_range_scale", models.IntegerField(blank=True, null=True)),
                (
                    "eask_book_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("datetime_approved", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.CharField(blank=True, max_length=50, null=True)),
                ("datetime_closed", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.CharField(blank=True, max_length=50, null=True)),
                ("trigger_remarks", models.TextField(blank=True, null=True)),
                ("user_remarks", models.TextField(blank=True, null=True)),
                ("eask_serial", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "ILMS_moitemequipment",
            },
        ),
        migrations.CreateModel(
            name="MoMappingTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "ILMS_momoapping",
            },
        ),
        migrations.CreateModel(
            name="MOPlannedSparesDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ILMS_moplannedsparesdescription",
            },
        ),
        migrations.CreateModel(
            name="PlannedMOSpareList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_number",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("quantity_required", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ILMS_plannedmosparelist",
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_type", models.CharField(blank=True, max_length=50, null=True)),
                ("price_date", models.DateField(blank=True, null=True)),
                ("price_ref", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price_cc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("qty", models.IntegerField(blank=True, null=True)),
                ("datetime_approved", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "station_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "ILMS_price",
            },
        ),
        migrations.CreateModel(
            name="PTSDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "in_progress_status",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "pts_number",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_pts", models.BooleanField(default=False)),
                ("is_sync", models.BooleanField(default=False)),
                ("is_hod", models.BooleanField(default=False)),
                ("is_hod_approval", models.BooleanField(default=False)),
                ("mo_pts_status", models.CharField(default="Pending", max_length=200)),
            ],
            options={
                "db_table": "ILMS_ptsdetails",
            },
        ),
        migrations.CreateModel(
            name="SurveyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demand_number",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "in_progress_status",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_survey", models.BooleanField(default=False)),
                ("is_sync", models.BooleanField(default=False)),
                ("is_hod", models.BooleanField(default=False)),
                ("is_hod_approval", models.BooleanField(default=False)),
                (
                    "mo_survey_status",
                    models.CharField(default="Pending", max_length=200),
                ),
            ],
            options={
                "db_table": "ILMS_surveydetails",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "vendor_code",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "vendor_class",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "manufacturer_priority",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("addressee", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=555, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=555, null=True),
                ),
                (
                    "address_line3",
                    models.CharField(blank=True, max_length=555, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("pin_code", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("datetime_approved", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date_banned_upto", models.DateField(blank=True, null=True)),
                (
                    "section_head",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "kompass_control_no",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "station_code",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ncage", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "gem_seller_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "business_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "def_proc_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "msme_registration_no",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("gst_no", models.CharField(blank=True, max_length=200, null=True)),
                ("pan", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "ILMS_vendor",
            },
        ),
        migrations.CreateModel(
            name="VendorList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendorcode", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "class_field",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "manufacturerpriority",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("addressee", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "addressline1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "addressline2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "addressline3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("pincode", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "countrycode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "datetimeapproved",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approvedby", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "datebannedupto",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sectionhead",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "kompasscontrolno",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stationcode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ncage", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gemsellerid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "businesstype",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("defprocid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "msmeregistrationno",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gstno", models.CharField(blank=True, max_length=255, null=True)),
                ("pan", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "ILMS_vendor_list",
            },
        ),
        migrations.CreateModel(
            name="VendorPil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eqpt_code", models.CharField(blank=True, max_length=100, null=True)),
                ("eqpt_desc", models.CharField(blank=True, max_length=255, null=True)),
                ("oem_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "vendor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vendor_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "characteristics_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("char_value", models.CharField(blank=True, max_length=255, null=True)),
                ("item_code", models.CharField(blank=True, max_length=100, null=True)),
                ("item_desc", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "substitute_item_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "substitute_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("eask_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "currency_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ved_cat", models.CharField(blank=True, max_length=50, null=True)),
                ("make_model", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ILMS_vendor_pil",
            },
        ),
        migrations.CreateModel(
            name="CustomerEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_ship_fit", models.IntegerField(blank=True, null=True)),
                ("qty_present", models.IntegerField(blank=True, null=True)),
                ("date_quantity_present", models.DateField(blank=True, null=True)),
                ("added_by", models.CharField(blank=True, max_length=50, null=True)),
                ("datetime_added", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.CharField(blank=True, max_length=50, null=True)),
                ("datetime_approved", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.CharField(blank=True, max_length=50, null=True)),
                ("datetime_closed", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ilms.customer"
                    ),
                ),
            ],
            options={
                "db_table": "ILMS_customerequipment",
            },
        ),
    ]
