# Generated by Django 5.2.15 on 2026-08-09 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ilms", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="item",
            table="ILMS_item",
        ),
        migrations.AlterModelTable(
            name="momappingtable",
            table="ILMS_momappingtable",
        ),
    ]
