# Generated by Django 5.2.15 on 2026-08-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TagIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagin_date", models.DateField(blank=True, null=True)),
                ("tagin_description", models.TextField(blank=True, null=True)),
                (
                    "tagin_maintainer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("all_items_returned", models.BooleanField(default=True)),
                ("items_pending", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("pending", "Pending"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("tagin_remarks", models.TextField(blank=True, null=True)),
                (
                    "tagin_maintainer_name_rank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "inout_tagin",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="TagInApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_on", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "inout_tagin_approval",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="TagOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now=True, null=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                ("modified_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "active",
                    models.SmallIntegerField(
                        choices=[(1, "active"), (2, "Inactive"), (3, "Delete")],
                        default=1,
                    ),
                ),
                (
                    "tagout_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "name_of_subsystem",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "name_of_component",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "serial_number_of_component",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pattern_number_of_component",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "weight_of_component",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("danger", "Danger"), ("warning", "Warning")],
                        default="danger",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ops", "Ops"),
                            ("non_ops", "Non Ops"),
                            ("partially_ops", "Partially Ops"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("special_instructions", models.TextField(blank=True, null=True)),
                ("expected_date_of_tagin", models.DateField(blank=True, null=True)),
                (
                    "tagout_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ty_loan_rtlapp", "Ty Loan/RTLAPP"),
                            ("survey_and_demand", "Survey & Demand"),
                            ("repair_or_overhauling", "Repair/Overhauling"),
                            ("consumable_survery", "Consumable Survey"),
                            ("aber_replacement", "ABER Replacement"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("tagout_description", models.TextField(blank=True, null=True)),
                (
                    "tagout_maintainer_name_rank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ty_loan_ship",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ty_authority",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ty_item_taken_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ty_additional_items", models.TextField(blank=True, null=True)),
                (
                    "survery_demand_authority",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "repair_ra_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("repair_landed_details", models.TextField(blank=True, null=True)),
                (
                    "repair_item_taken_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("repair_additional_items", models.TextField(blank=True, null=True)),
                (
                    "aber_authority",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "replacement_item",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("estimated_bom_arrival_date", models.DateField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_progress", "In Progress"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="in_progress",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("approved_on", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "inout_tagout",
                "ordering": ["-created_on"],
            },
        ),
    ]
