# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inout_tag", "0001_initial"),
        ("master", "0002_initial"),
        ("sfd", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taginapproval",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tagins",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="taginapproval",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tagin_approvals",
                to="master.department",
            ),
        ),
        migrations.AddField(
            model_name="taginapproval",
            name="tagin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagin_approvals",
                to="inout_tag.tagin",
            ),
        ),
        migrations.AddField(
            model_name="tagout",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tagouts",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="tagout",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_user",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="tagout",
            name="departments_affected",
            field=models.ManyToManyField(
                blank=True, related_name="affected_tagouts", to="master.department"
            ),
        ),
        migrations.AddField(
            model_name="tagout",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modified_user",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="tagout",
            name="tagout_equipment_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tagouts",
                to="sfd.shipequipment",
            ),
        ),
        migrations.AddField(
            model_name="tagout",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagouts",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="tagin",
            name="tagout",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagin",
                to="inout_tag.tagout",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taginapproval",
            unique_together={("tagin", "department")},
        ),
    ]
