# Generated by Django 5.2.15 on 2026-08-10 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inout_tag", "0002_initial"),
        ("master", "0003_alter_chmastersymptoms_department_and_more"),
        ("sfd", "0005_add_new_sfd_addon_fields_and_tables"),
        ("users", "0002_alter_loginregistrationimage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagin",
            options={"ordering": ("-created_on",)},
        ),
        migrations.AlterModelOptions(
            name="taginapproval",
            options={"ordering": ("-created_on",)},
        ),
        migrations.AlterModelOptions(
            name="tagout",
            options={"ordering": ("-created_on",)},
        ),
        migrations.AddField(
            model_name="tagin",
            name="active",
            field=models.SmallIntegerField(
                choices=[(1, "active"), (2, "Inactive"), (3, "Delete")], default=1
            ),
        ),
        migrations.AddField(
            model_name="tagin",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_user",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="tagin",
            name="created_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tagin",
            name="created_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="tagin",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modified_user",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="tagin",
            name="modified_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tagin",
            name="modified_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="taginapproval",
            name="active",
            field=models.SmallIntegerField(
                choices=[(1, "active"), (2, "Inactive"), (3, "Delete")], default=1
            ),
        ),
        migrations.AddField(
            model_name="taginapproval",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_user",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="taginapproval",
            name="created_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taginapproval",
            name="created_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="taginapproval",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modified_user",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="taginapproval",
            name="modified_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taginapproval",
            name="modified_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="tagin",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tagin",
            name="tagin_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="tagin",
            name="tagin_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tagin",
            name="tagin_maintainer",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="taginapproval",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagin_approvals",
                to="master.department",
            ),
        ),
        migrations.AlterField(
            model_name="taginapproval",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tagout",
            name="approval_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="in_progress",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tagout",
            name="departments_affected",
            field=models.ManyToManyField(
                related_name="affected_tagouts", to="master.department"
            ),
        ),
        migrations.AlterField(
            model_name="tagout",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tagout",
            name="tagout_equipment_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagout_equipment",
                to="sfd.shipequipment",
            ),
        ),
    ]
