# Generated by Django 5.2.15 on 2026-08-10 05:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inout_tag", "0003_alter_tagin_options_alter_taginapproval_options_and_more"),
        ("master", "0003_alter_chmastersymptoms_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagin",
            name="tagin_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="tagin",
            name="tagin_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="tagin",
            name="tagin_maintainer",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="taginapproval",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagin_approvals",
                to="master.department",
            ),
        ),
    ]
