# Generated by Django 5.2.17 on 2026-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inout_tag",
            "0004_alter_tagin_tagin_date_alter_tagin_tagin_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagin",
            name="approval_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending CO Approval"),
                    ("pending_hod", "Pending HOD Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tagin",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taginapproval",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending CO Approval"),
                    ("pending_hod", "Pending HOD Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tagout",
            name="approval_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending CO Approval"),
                    ("pending_hod", "Pending HOD Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="in_progress",
                max_length=20,
                null=True,
            ),
        ),
    ]
