from django.urls import path

from ems import views
from swmmapi.views import (
    CompletedRoutineSyncAPIView,
    FussDataSaveAPI,
    InitiateFussSyncAPIView,
    RoutineDARTSyncAPI,
)

from .views import (
    AberTriggerListAPIView,
    FussTriggerListAPIView,
    GenerateDL1APIView,
    SearchResultCalenderBasedLessThanSixMonthsAPIView,
    SearchResultRunningHoursBasedLessThanOneKAPIView,
    UniqueMaintopAPIView,
)

app_name = "ems"

urlpatterns = [
    path("section_name/", views.GetSectionNameAPIView.as_view(), name="getsectionname"),
    path(
        "section_name/<int:department_id>/",
        views.GetSectionNameAPIView.as_view(),
        name="getsectionname_pk",
    ),
    path(
        "equipment_name/",
        views.GetEquipmentNameAPIView.as_view(),
        name="getequipmentname",
    ),
    path(
        "equipment_name/<int:section_id>/",
        views.GetEquipmentNameAPIView.as_view(),
        name="getequipmentname_pk",
    ),
    path(
        "srar_equipment_name/",
        views.GetSrarEquipmentNameAPIView.as_view(),
        name="srar_getequipmentname",
    ),
    path(
        "srar_equipment_name/<int:section_id>/",
        views.GetSrarEquipmentNameAPIView.as_view(),
        name="srar_getequipmentname_pk",
    ),
    path(
        "equipment_name_rhsi/",
        views.GetEquipmentNameWithoutRhsiNullRowsAPIView.as_view(),
        name="getequipmentnamerhsi",
    ),
    path(
        "equipment_name_rhsi/<int:section_id>/",
        views.GetEquipmentNameWithoutRhsiNullRowsAPIView.as_view(),
        name="getequipmentnamerhsi_pk",
    ),
    path("routine_name/", views.GetRoutineNameAPIView.as_view(), name="getroutinename"),
    path(
        "routine_name/<int:equipment_name_id>/<str:routine_category>/",
        views.GetRoutineNameAPIView.as_view(),
        name="getroutinename_pk",
    ),
    path("create_section/", views.SectionCreateAPIView.as_view(), name="createsection"),
    path(
        "create_equipment/",
        views.EquipmentCreateAPIView.as_view(),
        name="createequipment",
    ),
    path(
        "create_total_running_hrs/",
        views.TotalRunningHoursCreateAPIView.as_view(),
        name="totalrunninghoursinput",
    ),
    path(
        "monthly_save/",
        views.MonthlyRunningHoursSaveAPIView.as_view(),
        name="monthlyrunningsave",
    ),
    path(
        "get_equipment_history/<int:pk>/",
        views.GetEquipmentHistoryJsonAPIView.as_view(),
        name="get_equipment_history",
    ),
    path(
        "update_equipment_state/",
        views.UpdateEquipmentStateAPIView.as_view(),
        name="update_equipment_state",
    ),
    path(
        "initiate_close_routine/<int:pk>/",
        views.InitiateCloseRoutineAPIView.as_view(),
        name="initiate_close_routine",
    ),
    path(
        "complete_routine/<int:pk>/",
        views.InitiateCloseRoutineAPIView.as_view(),
        name="complete_routine",
    ),
    path(
        "plan_routine/<int:pk>/", views.PlanRoutineAPIView.as_view(), name="Planroutine"
    ),
    path(
        "plan_routine_save/<int:pk>/",
        views.PlanRoutineSaveAPIView.as_view(),
        name="plan_routine_save",
    ),
    path(
        "plan_routine_multi_save/",
        views.PlanRoutineMultiSaveAPIView.as_view(),
        name="plan_routine_multi_save",
    ),
    path(
        "delete_planned_routine/<int:pk>/",
        views.DeletePlannedRoutineAPIView.as_view(),
        name="DeletePlanned_routine",
    ),
    path("search/", views.SearchMergedAPIView.as_view(), name="search"),
    path("search_detail/", views.SearchDetailAPIView.as_view(), name="search_detail"),
    path(
        "search_detail/<int:pk>/",
        views.SearchDetailAPIView.as_view(),
        name="search_detail_pk",
    ),
    path(
        "planned-routines/",
        views.PlannedRoutinesMasterFunctionAPIView.as_view(),
        name="planned_routines_master",
    ),
    path(
        "get-routine-names/",
        views.GetRoutineNamesAPIView.as_view(),
        name="get_routine_names",
    ),
    path(
        "routine-name/",
        views.GetRoutineNameSingleAPIView.as_view(),
        name="routine_name",
    ),
    path(
        "get-equipment-by-section/",
        views.GetEquipmentBySectionAPIView.as_view(),
        name="get_equipment_by_section",
    ),
    path("mulraisefuss/", views.MulRaiseFussAPIView.as_view(), name="mulraisefuss"),
    path(
        "fuss_raised_details/",
        views.FussRaisedDetailsAPIView.as_view(),
        name="fuss_raised_details",
    ),
    path(
        "fuss_raised_routines/",
        views.FussRaisedRoutinesAPIView.as_view(),
        name="fuss_raised_routines",
    ),
    path(
        "fuss_trigger_list/",
        FussTriggerListAPIView.as_view(),
        name="fuss_trigger_list",
    ),
    path(
        "aber_trigger_list/",
        AberTriggerListAPIView.as_view(),
        name="aber_trigger_list",
    ),
    path("slip-history/", views.SlipHistoryAPIView.as_view(), name="history"),
    path(
        "slip-history/<int:activate_btn>/",
        views.SlipHistoryAPIView.as_view(),
        name="history_activate",
    ),
    path(
        "addroutine_details/",
        views.add_routine_details,
        name="addroutinedetails",
    ),
    path(
        "add_routine_desc/",
        views.add_routine_description,
        name="addroutinedescription",
    ),
    path("edit_routine_name/", views.edit_routine_name, name="edit_routinename"),
    path(
        "edit_equipment_name/",
        views.edit_equipment_name,
        name="edit_equipmentname",
    ),
    path(
        "ops_master/create_routine_frequency/",
        views.create_routine_frequency,
        name="create_routine_frequency",
    ),
    path(
        "ops_master/create_equipment_name/",
        views.create_equipment_name,
        name="create_equipment_name",
    ),
    path("ops_master/", views.equipment_state_list, name="ops_master"),
    path(
        "search_forstatechange/",
        views.equipment_state_list,
        name="search_for_statechange",
    ),
    path(
        "searchforstatechange_merge/",
        views.equipment_state_list,
        name="searchforstatechange_merge",
    ),
    path(
        "search_result_forstatechange/",
        views.equipment_state_list,
        name="search_result_for_statechange",
    ),
    path("thumbnail/", views.thumbnail_data, name="thumbnail"),
    path(
        "barchart/<int:section_name>/",
        views.section_rhsi_barchart,
        name="barchart_view",
    ),
    path("active_users/", views.active_users, name="list_active_users"),
    path("maintop-pdf/<int:pk>/", views.maintop_pdf, name="maintop_pdf"),
    path("fuss-pdf/<int:pk>/", views.fuss_pdf, name="fuss_pdf"),
    path("lessroutinesearch/", views.less_routine_search, name="lessroutinesearch"),
    path(
        "lesssearchview/",
        views.less_routine_search_detail,
        name="lesssearchview",
    ),
    path(
        "lesssearchview/<int:pk>/",
        views.less_routine_search_detail,
        name="lesssearchview_pk",
    ),
    path(
        "combined-routines/",
        views.combined_routine_search,
        name="combined_routine_search",
    ),
    path("import/", views.routine_cmms_sync_disabled, name="import_excel_file"),
    path(
        "import_missing/",
        views.routine_cmms_sync_disabled,
        name="import_missing_routines",
    ),
    path(
        "export_routine_excel/",
        views.export_routine_excel,
        name="export_routine_excel",
    ),
    path(
        "initiate_excel_file/",
        views.routine_cmms_sync_disabled,
        name="initiate_excel_file",
    ),
    path("create_datapoints/", views.save_oem_data_point, name="datapointsinput"),
    path("create_graph/", views.oem_graph_data, name="graphgenerator"),
    path("slip_calc/", views.calculate_gt_slip, name="slipview"),
    path("save_slip/", views.save_gt_slip, name="saveslipview"),
    path("slip_limit/", views.save_slip_limit, name="sliplimitinput"),
    path(
        "export_dl1_accdb_ndmbi/",
        views.dl1_accdb_export_disabled,
        name="export_dl1_accdb_ndmbi",
    ),
    path(
        "export_dl1_accdb_ndv/",
        views.dl1_accdb_export_disabled,
        name="export_dl1_accdb_ndv",
    ),
    path(
        "export_dl1_accdb_nsrykoc/",
        views.dl1_accdb_export_disabled,
        name="export_dl1_accdb_nsrykoc",
    ),
    path(
        "export_dl1_accdb_nsrykar/",
        views.dl1_accdb_export_disabled,
        name="export_dl1_accdb_nsrykar",
    ),
    path(
        "export_dl1_accdb_nsrypdr/",
        views.dl1_accdb_export_disabled,
        name="export_dl1_accdb_nsrypdr",
    ),
    path(
        "routine_history/",
        views.RoutineHistoryAPIView.as_view(),
        name="routine_history",
    ),
    path(
        "equipment_running_history/",
        views.EquipmentRunningHistoryAPIView.as_view(),
        name="equipment_running_history",
    ),
    path(
        "weekly_maintenance_plan/",
        views.MaintenancePlanAPIView.as_view(),
        {"period": "weekly"},
        name="weekly_maintenance_plan",
    ),
    path(
        "maintenance_plan/<str:period>/",
        views.MaintenancePlanAPIView.as_view(),
        name="maintenance_plan",
    ),
    path(
        "routine_history_timeline_data/<int:pk>/",
        views.RoutineHistoryTimelineDataAPIView.as_view(),
        name="routine_history_timeline_data",
    ),
    path(
        "result_specific_runninghr/",
        SearchResultRunningHoursBasedLessThanOneKAPIView.as_view(),
        name="result_specific_runninghr",
    ),
    path(
        "result_specific_calender/",
        SearchResultCalenderBasedLessThanSixMonthsAPIView.as_view(),
        name="result_specific_calender",
    ),
    path(
        "search_detail_plan/",
        views.SearchDetailPlanAPIView.as_view(),
        name="search_detail_planned",
    ),
    path(
        "search_detail_plan/<int:pk>/",
        views.SearchDetailPlanAPIView.as_view(),
        name="search_detail_planned_pk",
    ),
    path(
        "close_raise_fuss/<int:pk>/",
        views.CloseRaiseFussAPIView.as_view(),
        name="close_raise_fuss",
    ),
    path(
        "complete_fuss/<int:pk>/",
        views.CompleteFussFunctionAPIView.as_view(),
        name="complete_fuss",
    ),
    path(
        "save-oem-spare/",
        views.SaveOemSpareFunctionAPIView.as_view(),
        name="save_oem_spare",
    ),
    path(
        "closed_routines_list/",
        views.ClosedRoutinesListAPIView.as_view(),
        name="closed_routines_list",
    ),
    path(
        "history_close_routine/",
        views.HistoryCloseRoutineAPIView.as_view(),
        name="history_close_routine",
    ),
    path(
        "closeroutinehistory/",
        views.HistoryCloseRoutineAPIView.as_view(),
        name="history_close_routine_legacy",
    ),
    path(
        "routine_init_data/",
        views.UniqueMaintopAPIView.as_view(),
        name="routine_init_data",
    ),
    path(
        "save_routine_init/",
        views.SaveRoutineInitializationRowFunctionAPIView.as_view(),
        name="save_routine_init",
    ),
    path(
        "get_routine_init_details/",
        views.GetRoutineInitDetailsFunctionAPIView.as_view(),
        name="get_routine_init_details",
    ),
    path(
        "get_routine_init_details/<int:id>/",
        views.GetRoutineInitDetailsFunctionAPIView.as_view(),
        name="get_routine_init_details_by_id",
    ),
    path(
        "save_routine_init_bulk/",
        views.SaveRoutineInitBulkFunctionAPIView.as_view(),
        name="save_routine_init_bulk",
    ),
    path(
        "unique_maintop/",
        UniqueMaintopAPIView.as_view(),
        name="unique_maintop",
    ),
    path(
        "generatedl1/",
        GenerateDL1APIView.as_view(),
        name="generatedl1",
    ),
    path(
        "generatedl1_list/",
        views.EmsGeneratedReportsListFunctionAPIView.as_view(),
        name="generatedl1_list",
    ),
    path(
        "report_inner_rows/<int:id>/",
        views.EmsReportInnerRowsFunctionAPIView.as_view(),
        name="report_inner_rows",
    ),
    path(
        "save_dl_draft_rows/",
        views.SaveDlDraftRowsFunctionAPIView.as_view(),
        name="save_dl_draft_rows",
    ),
    path(
        "delete_dl_draft_row/",
        views.DeleteDlDraftRowFunctionAPIView.as_view(),
        name="delete_dl_draft_row",
    ),
    path(
        "get_manual_names/",
        views.GetManualNamesFunctionAPIView.as_view(),
        name="get_manual_names",
    ),
    path(
        "lookup_fuel_sounding/",
        views.LookupFuelSoundingFunctionAPIView.as_view(),
        name="lookup_fuel_sounding",
    ),
]


integration_urlpatterns = [
    path("fuss_sync/", FussDataSaveAPI.as_view(), name="fuss_sync_cmms"),
    path(
        "initiate-fuss-sync/<int:pk>/",
        InitiateFussSyncAPIView.as_view(),
        name="initiate-fuss-sync",
    ),
    path(
        "completed-routine-sync/",
        CompletedRoutineSyncAPIView.as_view(),
        name="completed-routine-sync",
    ),
    path(
        "receive_completed_routine/",
        RoutineDARTSyncAPI.as_view(),
        name="receive_completed_routine",
    ),
]
