# Generated by Django 5.2.15 on 2026-08-13 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master", "0004_alter_subdepartment_description"),
        ("sfd", "0006_add_new_sfd_addon_fields_and_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="DLTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("defect_no", models.CharField(blank=True, max_length=100, null=True)),
                ("dl_type", models.CharField(blank=True, max_length=255, null=True)),
                ("equip_name", models.CharField(blank=True, max_length=255, null=True)),
                ("dart_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "defect_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "ship_remarks",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "yard_remarks",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("final_prm", models.CharField(blank=True, max_length=255, null=True)),
                ("c_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "remarks_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("view_wi", models.CharField(blank=True, max_length=255, null=True)),
                ("interact", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "wi_generation_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "qc_clearance",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "wi_closing_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "wi_generated_by_yard",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "weekly_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("defect_key", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "equip_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("equip_sys", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="Not yet started", max_length=50, null=True
                    ),
                ),
                (
                    "dl_importance",
                    models.CharField(
                        blank=True, default="Normal DL", max_length=50, null=True
                    ),
                ),
                (
                    "current_status_updated_on",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("critical", models.BooleanField(blank=True, default=False, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "ship_equip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfd.shipequipment",
                    ),
                ),
                (
                    "sub_dept_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.subdepartment",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DLClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("er_date_by_yard", models.DateField(blank=True, null=True)),
                ("start_work_by_yard", models.DateField(blank=True, null=True)),
                ("complete_work_by_yard", models.DateField(blank=True, null=True)),
                ("dl_work", models.IntegerField(blank=True, null=True)),
                (
                    "dl_tracker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dl_close",
                        to="dl_monitor.dltracker",
                    ),
                ),
            ],
        ),
    ]
