from django.urls import path

from .views import (
    CMMSFDDataAPI,
    CMMSRoutineDataAPI,
    CMMSDefectDataAPI,
    CMMSLessRoutineDataAPI,
    MissingRoutinesAPIView,
    SaveCMMSDefectsAPI,
    CMMSDefectSyncAPI,
    InitiateDARTDataSaveAPI,
    InitiateDartSyncAPIView,
    CompleteDARTUpdateAPI,
    CompleteDartSyncAPIView,
    FussDataSaveAPI,
    CompletedRoutineSyncAPIView,
    RoutineDARTSyncAPI,
    InitiateFussSyncAPIView,
    SRARSyncAPIView,
    SRARSyncByMonthYearAPIView,
    SRARDataSaveAPI,
    SRARPullFromCMMSAPIView,
    CMMSMasterEquipmentTypeSyncAPI,
)

app_name = "swmmapi"

urlpatterns = [
    path(
        "sfd/join-data",
        CMMSFDDataAPI.as_view(),
        name="routine_join_data_sfd",
    ),
    path(
        "routine/join-data/",
        CMMSRoutineDataAPI.as_view(),
        name="routine_join_data",
    ),
    path(
        "defect/join-data/",
        CMMSDefectDataAPI.as_view(),
        name="defect_join_data",
    ),
    path(
        "routine/less-than-data/",
        CMMSLessRoutineDataAPI.as_view(),
        name="less_than_routine_join_data",
    ),
    path(
        "routine/missing-data/",
        MissingRoutinesAPIView.as_view(),
        name="missing_routines_data",
    ),
    path(
        "defect/save/",
        SaveCMMSDefectsAPI.as_view(),
        name="save_cmms_defects",
    ),
    path(
        "defect/sync/",
        CMMSDefectSyncAPI.as_view(),
        name="defect_sync",
    ),
    path(
        "dart/dart_initiate/",
        InitiateDARTDataSaveAPI.as_view(),
        name="dart_initiate",
    ),
    path(
        "dart/complete/",
        CompleteDARTUpdateAPI.as_view(),
        name="dart_complete",
    ),
    path(
        "initiate-dart-sync/<int:pk>/",
        InitiateDartSyncAPIView.as_view(),
        name="initiate-dart-sync",
    ),
    path(
        "complete-dart-sync/<int:pk>/",
        CompleteDartSyncAPIView.as_view(),
        name="complete-dart-sync",
    ),
    path(
        "fuss_sync/",
        FussDataSaveAPI.as_view(),
        name="fuss_sync",
    ),
    path(
        "initiate-fuss-sync/<int:pk>/",
        InitiateFussSyncAPIView.as_view(),
        name="initiate-fuss-sync",
    ),
    path(
        "completed-routine-sync/",
        CompletedRoutineSyncAPIView.as_view(),
        name="completed-routine-sync",
    ),
    path(
        "receive_completed_routine/",
        RoutineDARTSyncAPI.as_view(),
        name="receive_completed_routine",
    ),
    path(
        "srar_api/srar_sync_by_month_year/",
        SRARSyncByMonthYearAPIView.as_view(),
        name="srar_sync_by_month_year",
    ),
    path(
        "srar_api/srar_pull_from_cmms/",
        SRARPullFromCMMSAPIView.as_view(),
        name="srar_pull_from_cmms",
    ),
    path(
        "srar_api/srar_sync/<str:pk>/",
        SRARSyncAPIView.as_view(),
        name="srar_sync",
    ),
    path(
        "srar/save-srar/",
        SRARDataSaveAPI.as_view(),
        name="srar_data_save",
    ),
    path(
        "sfd/ch-master-equipment-type/sync/",
        CMMSMasterEquipmentTypeSyncAPI.as_view(),
        name="ch_master_equipment_type_sync",
    ),
]
