# Generated by Django 5.2.15 on 2026-08-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("defect", "Defect"),
                            ("routine", "Routine"),
                            ("trial", "Trial"),
                            ("audit", "Audit"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="event_docs/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlannerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "lane",
                    models.CharField(
                        choices=[
                            ("eng", "Engineering"),
                            ("elec", "Electrical"),
                            ("wpn", "Weapon"),
                            ("ops", "Operations"),
                            ("fmu", "FMU / Support"),
                            ("tri", "Trials & Inspection"),
                            ("adm", "Admin / Other"),
                        ],
                        default="eng",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("defect", "Defect"),
                            ("routine", "Routine"),
                            ("planned_routine", "Planned Routine"),
                            ("trial", "Trials / Inspections"),
                            ("audit", "Audit"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("delayed", "Delayed"),
                            ("conflict", "Conflict"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
                ("delayed", models.BooleanField(default=False)),
                ("conflict", models.BooleanField(default=False)),
                ("selected", models.BooleanField(default=False)),
                ("isolation", models.BooleanField(default=False)),
                ("equipment", models.CharField(blank=True, max_length=255, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date", "start_time", "id"],
            },
        ),
    ]
