# Generated by Django 5.2.15 on 2026-08-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_planner", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(db_column="date"),
        ),
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, db_column="EndDate", null=True),
        ),
    ]
