from django.urls import path
from swmmapi.views import (
    CompleteDartSyncAPIView,
    CompleteDARTUpdateAPI,
    InitiateDARTDataSaveAPI,
    InitiateDartSyncAPIView,
    SaveCMMSDefectsAPI,
)

from .views import (
    AddDartFromOBSAPIView,
    AddDartMetadataAPIView,
    AllDataOfRAAPIView,
    CheckExistingSparesAPIView,
    CompleteDartListAPIView,
    CompleteDefectAPIView,
    CreateDLFunAPIView,
    CreateRAAjaxAPIView,
    CreateRADLFunAPIView,
    DartDashboardAPIView,
    DartHistoryDefaultDataAPIView,
    DartHistoryDetailAPIView,
    DartHistoryFilteredDataAPIView,
    DartHistoryPDFAPIView,
    DeleteDLRowAPIView,
    ExportPendingDefectsDL2APIView,
    GeneratedDLIIReportExportAPIView,
    GeneratedDLIIReportRowsAPIView,
    GeneratedDLIIReportsAPIView,
    GetDartDetailsAPIView,
    GetDartSparesDataAPIView,
    GetEquipmentObjectsAPIView,
    GetNomenclatureDetailsAPIView,
    GetRefitPeriodsAPIView,
    GetSubDeptDefectsAPIView,
    GuaranteeDefectPDFAPIView,
    InitiateDartAPIView,
    MaintenancePeriodsListAPIView,
    MergeInitiateDefectsAPIView,
    MoveToDraftAPIView,
    PendingDefectAPIView,
    PendingDefectsExportAPIView,
    PendingDefectsXLSXExportAPIView,
    RADefectListAPIView,
    RefitOperationalOccasionAPIView,
    SaveDLRowsAPIView,
    SaveOEMSpareAPIView,
)

app_name = "radl_master"

urlpatterns = [
    path("", DartDashboardAPIView.as_view(), name="home"),
    path("pending_defect/", PendingDefectAPIView.as_view(), name="defectpending"),
    path(
        "export/xlsx/",
        PendingDefectsXLSXExportAPIView.as_view(),
        name="export_pending_defects_xlsx",
    ),
    path(
        "export/accdb/",
        PendingDefectsExportAPIView.as_view(),
        name="export_pending_defects_access",
    ),
    path("ra_defect_list/", RADefectListAPIView.as_view(), name="ra_defect_list"),
    path(
        "check_existing_spares/",
        CheckExistingSparesAPIView.as_view(),
        name="check_existing_spares",
    ),
    path(
        "complete_dart_list/",
        CompleteDartListAPIView.as_view(),
        name="complete_dart_list",
    ),
    path(
        "merge_initiate_defects/",
        MergeInitiateDefectsAPIView.as_view(),
        name="merge_initiate_defects",
    ),
    path(
        "complete_defect/<int:defect_id>/",
        CompleteDefectAPIView.as_view(),
        name="complete_defect",
    ),
    path("raisesignal/", DartDashboardAPIView.as_view(), name="raisesignal"),
    path("add_dart/", AddDartMetadataAPIView.as_view(), name="add_dart"),
    path(
        "add_dart_from_obs/",
        AddDartFromOBSAPIView.as_view(),
        name="add_dart_from_obs",
    ),
    path("initiate_dart/", InitiateDartAPIView.as_view(), name="initiate_dart"),
    path("initiate_dart/", InitiateDartAPIView.as_view(), name="api_initiate_dart"),
    path(
        "dart/get-refit-periods/",
        GetRefitPeriodsAPIView.as_view(),
        name="get_refit_periods",
    ),
    path(
        "generate_ra_signal/",
        DartDashboardAPIView.as_view(),
        name="generate_ra_signal",
    ),
    path(
        "get-equipment-objects/",
        GetEquipmentObjectsAPIView.as_view(),
        name="get_equipment_objects",
    ),
    path(
        "get_nomenclature_details/",
        GetNomenclatureDetailsAPIView.as_view(),
        name="get_nomenclature_details",
    ),
    path("drafdetailsview/", RADefectListAPIView.as_view(), name="drafdetailsview"),
    path("closeddart/", CompleteDartListAPIView.as_view(), name="closeddart"),
    path("createdlfun/", CreateDLFunAPIView.as_view(), name="createdlfun"),
    path("darthistory/", DartHistoryDefaultDataAPIView.as_view(), name="darthistory"),
    path("history/", DartHistoryDefaultDataAPIView.as_view(), name="history"),
    path("dartdashboard/", DartDashboardAPIView.as_view(), name="dartdashboard"),
    path("create_ra/", CreateRADLFunAPIView.as_view(), name="create_ra"),
    path("all_data_of_ra/", AllDataOfRAAPIView.as_view(), name="all_data_of_ra"),
    path(
        "export_pending_defects_accdb/",
        PendingDefectsExportAPIView.as_view(),
        name="export_pending_defects_accdb",
    ),
    path("create-ra-ajax/", CreateRAAjaxAPIView.as_view(), name="create_ra_ajax"),
    path("move_to_draft/", MoveToDraftAPIView.as_view(), name="move_to_draft"),
    path(
        "history/data/",
        DartHistoryDefaultDataAPIView.as_view(),
        name="history_data",
    ),
    path(
        "history/filtered_data/",
        DartHistoryFilteredDataAPIView.as_view(),
        name="history_filtered_data",
    ),
    path(
        "refit_and_operational_occation/",
        RefitOperationalOccasionAPIView.as_view(),
        name="refit_operational_occation",
    ),
    path("save_dl_rows/", SaveDLRowsAPIView.as_view(), name="save_dl_rows"),
    path("delete_dl_row/", DeleteDLRowAPIView.as_view(), name="delete_dl_row"),
    path(
        "generate_report/",
        GeneratedDLIIReportsAPIView.as_view(),
        name="generate_report",
    ),
    path(
        "generated-dl-ii-reports/",
        GeneratedDLIIReportsAPIView.as_view(),
        name="generated-dl-ii-reports",
    ),
    path(
        "report_inner_rows/<int:report_id>/",
        GeneratedDLIIReportRowsAPIView.as_view(),
        name="report_inner_rows",
    ),
    path(
        "report_inner_rows/<int:report_id>/",
        GeneratedDLIIReportRowsAPIView.as_view(),
        name="generated-dl-ii-report-rows",
    ),
    path(
        "export_existing_pending_defects_dl2_accdb/<int:report_id>/",
        GeneratedDLIIReportExportAPIView.as_view(),
        name="export_existing_pending_defects_dl2_accdb",
    ),
    path(
        "export_existing_pending_defects_dl2_accdb/<int:report_id>/",
        GeneratedDLIIReportExportAPIView.as_view(),
        name="generated-dl-ii-report-export",
    ),
    path(
        "export_pending_defects_dl2_accdb/",
        ExportPendingDefectsDL2APIView.as_view(),
        name="export_pending_defects_dl2_accdb",
    ),
    path(
        "export_pending_defects_dl2_ndv/",
        ExportPendingDefectsDL2APIView.as_view(),
        name="export_pending_defects_dl2_ndv",
    ),
    path(
        "export_pending_defects_dl2_nsrykar/",
        ExportPendingDefectsDL2APIView.as_view(),
        name="export_pending_defects_dl2_nsrykar",
    ),
    path(
        "export_pending_defects_dl2_nsrykoc/",
        ExportPendingDefectsDL2APIView.as_view(),
        name="export_pending_defects_dl2_nsrykoc",
    ),
    path(
        "export_pending_defects_dl2_nsrypbr/",
        ExportPendingDefectsDL2APIView.as_view(),
        name="export_pending_defects_dl2_nsrypbr",
    ),
    path(
        "gd_pdf/<int:dart_id>/",
        GuaranteeDefectPDFAPIView.as_view(),
        name="generate_guarantee_pdf",
    ),
    path(
        "get_dart_spares_data/",
        GetDartSparesDataAPIView.as_view(),
        name="get_dart_spares_data",
    ),
    path("save_oem_spare/", SaveOEMSpareAPIView.as_view(), name="save_oem_spare"),
    path(
        "get_sub_dept_defects/",
        GetSubDeptDefectsAPIView.as_view(),
        name="get_sub_dept_defects",
    ),
    path(
        "maintenance_periods/",
        MaintenancePeriodsListAPIView.as_view(),
        name="maintenance_periods_list",
    ),
    path("get_dart_details/", GetDartDetailsAPIView.as_view(), name="get_dart_details"),
    path(
        "history_detail/<int:id>/",
        DartHistoryDetailAPIView.as_view(),
        name="history_detail",
    ),
    path("history_pdf/<int:id>/", DartHistoryPDFAPIView.as_view(), name="history_pdf"),
]

integration_urlpatterns = [
    path("cmms/dart", SaveCMMSDefectsAPI.as_view(), name="cmms-dart-sync"),
    path(
        "initiate-dart-sync/<int:pk>/",
        InitiateDartSyncAPIView.as_view(),
        name="initiate-dart-sync",
    ),
    path(
        "complete-dart-sync/<int:pk>/",
        CompleteDartSyncAPIView.as_view(),
        name="complete-dart-sync",
    ),
    path(
        "dart/dart_initiate/",
        InitiateDARTDataSaveAPI.as_view(),
        name="dart_initiate_cmms",
    ),
    path(
        "dart/complete/",
        CompleteDARTUpdateAPI.as_view(),
        name="dart_complete_cmms",
    ),
]
