# Generated by Django 5.2.15 on 2026-08-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddRoutineDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "equipment_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nomenclature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("maintop_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dart_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("routine_no", models.CharField(blank=True, max_length=100, null=True)),
                ("by_whom", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "frequency_in_months",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "frequency_in_hours",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("rhs_i", models.CharField(blank=True, max_length=100, null=True)),
                ("rhs_i_updated_upto", models.DateField(blank=True, null=True)),
                (
                    "last_routine_commencement_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_routine_completion_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_routine_completion_atrunning_hrs",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("frequency", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "routine_category",
                    models.CharField(
                        choices=[
                            ("RUNNING HOUR BASED", "RUNNING HOUR BASED"),
                            ("CALENDAR BASED", "CALENDAR BASED"),
                            ("ALTERNATE PERIODIC", "ALTERNATE PERIODIC"),
                        ],
                        default="RUNNING HOUR BASED",
                        max_length=200,
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, default="", max_length=3000, null=True
                    ),
                ),
                ("converted", models.BooleanField(default=False)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataPointsAirprHPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hpc_rpm", models.FloatField(max_length=200)),
                ("air_pr_hpc", models.FloatField(max_length=200)),
                (
                    "amb_pressure",
                    models.FloatField(
                        blank=True, default="", max_length=200, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataPointsExtTemp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hpc_rpm", models.FloatField(max_length=200)),
                ("ext_temp", models.FloatField(max_length=200)),
                (
                    "amb_temp",
                    models.FloatField(
                        blank=True, default="", max_length=200, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataPointsExtTempGTG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("el_load", models.FloatField(max_length=200)),
                ("ext_temp", models.FloatField(max_length=200)),
                (
                    "amb_temp",
                    models.FloatField(
                        blank=True, default="", max_length=200, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataPointsGTLPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hpc_rpm", models.FloatField(default=None, max_length=200)),
                ("lpc_rpm", models.FloatField(default=None, max_length=200)),
                (
                    "amb_temp",
                    models.FloatField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "nomenclature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("extra", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "rhsi",
                    models.FloatField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                ("rhsi_updated_until", models.DateTimeField(blank=True, null=True)),
                ("start_timedate", models.DateTimeField(blank=True, null=True)),
                ("stop_timedate", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                        default="INACTIVE",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "started_at_location",
                    models.CharField(
                        choices=[
                            ("AT HARBOUR", "AT HARBOUR"),
                            ("AT SEA", "AT SEA"),
                            ("AT ANCHORAGE", "AT ANCHORAGE"),
                        ],
                        default="AT SEA",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "equipment_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_t_equipment_ship_detail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FussRaiseDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isclosed_fuss", models.BooleanField(default=False)),
                ("ship", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("serial_no", models.CharField(blank=True, max_length=50, null=True)),
                ("fuss_date", models.DateField(blank=True, null=True)),
                ("last_undertaken", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("schedule_date", models.DateField(blank=True, null=True)),
                ("equipment", models.TextField(blank=True, null=True)),
                (
                    "location_on_board",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "equipment_sr_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "maintop_no",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "frequency",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "amendment_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("new_equipment", models.BooleanField(default=False)),
                ("mos_wed", models.CharField(blank=True, max_length=100, null=True)),
                ("yard", models.CharField(blank=True, max_length=100, null=True)),
                ("last_smp_completed", models.DateField(blank=True, null=True)),
                (
                    "last_smp_duration",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_amp_completed", models.DateField(blank=True, null=True)),
                (
                    "last_amp_duration",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("amp_smp_required_wef", models.DateField(blank=True, null=True)),
                (
                    "amp_smp_duration",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("demand_details", models.TextField(blank=True, null=True)),
                ("sapres_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FussSpare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("quantity", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="LessAddRoutineDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "equipment_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nomenclature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("maintop_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dart_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("routine_no", models.CharField(blank=True, max_length=100, null=True)),
                ("by_whom", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "frequency_in_months",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "frequency_in_hours",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("rhs_i", models.CharField(blank=True, max_length=100, null=True)),
                ("rhs_i_updated_upto", models.DateField(blank=True, null=True)),
                (
                    "last_routine_commencement_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_routine_completion_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_routine_completion_atrunning_hrs",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("frequency", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "routine_category",
                    models.CharField(
                        choices=[
                            ("OCCASIONAL ROUTINES", "OCCASIONAL ROUTINES"),
                            ("DAILY ROUTINES", "DAILY ROUTINES"),
                            ("WEEKLY ROUTINES", "WEEKLY ROUTINES"),
                            ("MONTHLY ROUTINES", "MONTHLY ROUTINES"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, default="", max_length=3000, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessRoutineDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintop_no", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "dart_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "routine_no",
                    models.SlugField(blank=True, default="", max_length=500),
                ),
                ("routine_description", models.TextField()),
                ("by_whom", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="MaintopDetail",
            fields=[
                ("routine_id", models.IntegerField(primary_key=True, serialize=False)),
                ("routine_no", models.CharField(blank=True, max_length=100, null=True)),
                ("routine_description", models.TextField(blank=True, null=True)),
                ("routine_brief_description", models.TextField(blank=True, null=True)),
                ("maintop_id", models.IntegerField(blank=True, null=True)),
                ("maintop_no", models.CharField(blank=True, max_length=100, null=True)),
                ("amendment_no", models.IntegerField(blank=True, null=True)),
                ("frequency_id", models.IntegerField(blank=True, null=True)),
                ("frequency", models.CharField(blank=True, max_length=100, null=True)),
                ("frequency_sr_no", models.IntegerField(blank=True, null=True)),
                ("group_heading", models.TextField(blank=True, null=True)),
                ("para_heading", models.TextField(blank=True, null=True)),
                ("alternate_info", models.TextField(blank=True, null=True)),
                ("by_whom", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("dockyard_remarks", models.TextField(blank=True, null=True)),
                ("admin_remarks", models.TextField(blank=True, null=True)),
                ("jic_id", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                ("amendment_date", models.DateTimeField(blank=True, null=True)),
                ("by_whom_id1", models.IntegerField(blank=True, null=True)),
                ("by_whom_id2", models.IntegerField(blank=True, null=True)),
                ("by_whom_id3", models.IntegerField(blank=True, null=True)),
                ("freq_priority", models.IntegerField(blank=True, null=True)),
                (
                    "universal_id_a_user_created_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_a_user_updated_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_t_maintopdetail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_t_maintopheader",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_m_frequency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_t_maintopjic",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_m_bywhom1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_m_bywhom2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_m_bywhom3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("jic", models.CharField(blank=True, max_length=255, null=True)),
                ("ss_proposal", models.TextField(blank=True, null=True)),
                ("applicable_eqpt", models.TextField(blank=True, null=True)),
                ("insma_recommendations", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "routine_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ship_id", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("remove_reason", models.TextField(blank=True, null=True)),
                ("is_synced", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MaintopHeader",
            fields=[
                ("maintop_id", models.IntegerField(primary_key=True, serialize=False)),
                ("maintop_no", models.CharField(blank=True, null=True)),
                (
                    "maintop_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("original_date", models.DateTimeField(blank=True, null=True)),
                ("amendment_no", models.IntegerField(blank=True, null=True)),
                ("amendment_date", models.DateTimeField(blank=True, null=True)),
                ("authority", models.CharField(blank=True, max_length=500, null=True)),
                ("flag", models.BooleanField(blank=True, null=True)),
                ("active", models.BooleanField(blank=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=1000, null=True)),
                ("department", models.CharField(blank=True, max_length=10, null=True)),
                ("is_non_digitized", models.BooleanField(blank=True, null=True)),
                ("fuss_id", models.IntegerField(blank=True, null=True)),
                ("equipmentcode", models.TextField(blank=True, null=True)),
                (
                    "equipment_specification",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "ship_applicable",
                    models.CharField(blank=True, max_length=2500, null=True),
                ),
                ("documents", models.TextField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=500, null=True)),
                ("issue_date", models.DateTimeField(blank=True, null=True)),
                (
                    "universal_id_a_user_created_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_a_user_updated_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_t_maintopheader",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_t_fuss",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("authority_date", models.DateTimeField(blank=True, null=True)),
                ("is_draft", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementFuelsondingFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tank_type", models.CharField(blank=True, max_length=255, null=True)),
                ("tank_name", models.CharField(blank=True, max_length=255, null=True)),
                ("mm", models.FloatField()),
                ("volume", models.FloatField()),
                ("tone", models.FloatField(blank=True, null=True)),
                ("field_10mm", models.FloatField(blank=True, null=True)),
                ("field_20mm", models.FloatField(blank=True, null=True)),
                ("field_30mm", models.FloatField(blank=True, null=True)),
                ("field_40mm", models.FloatField(blank=True, null=True)),
                ("field_50mm", models.FloatField(blank=True, null=True)),
                ("field_60mm", models.FloatField(blank=True, null=True)),
                ("field_70mm", models.FloatField(blank=True, null=True)),
                ("field_80mm", models.FloatField(blank=True, null=True)),
                ("field_90mm", models.FloatField(blank=True, null=True)),
                ("field_100per", models.BooleanField(blank=True, null=True)),
                ("field_95per", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ems_measurement_fuelsonding_final",
            },
        ),
        migrations.CreateModel(
            name="PlannedAddRoutineDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "equipment_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nomenclature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("maintop_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dart_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("routine_no", models.CharField(blank=True, max_length=100, null=True)),
                ("by_whom", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "frequency_in_months",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "frequency_in_hours",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("rhs_i", models.CharField(blank=True, max_length=100, null=True)),
                ("rhs_i_updated_upto", models.DateField(blank=True, null=True)),
                (
                    "last_routine_commencement_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_routine_completion_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_routine_completion_atrunning_hrs",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("frequency", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "routine_category",
                    models.CharField(
                        choices=[
                            ("RUNNING HOUR BASED", "RUNNING HOUR BASED"),
                            ("CALENDAR BASED", "CALENDAR BASED"),
                            ("ALTERNATE PERIODIC", "ALTERNATE PERIODIC"),
                        ],
                        default="RUNNING HOUR BASED",
                        max_length=200,
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, default="", max_length=3000, null=True
                    ),
                ),
            ],
            options={
                "db_table": "ems_planned_addroutinedetails",
            },
        ),
        migrations.CreateModel(
            name="PlannedRoutineDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spares_required", models.BooleanField(default=False)),
                ("planned_commencement_date", models.DateField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ems_planned_routinedescription",
            },
        ),
        migrations.CreateModel(
            name="PostCalculateGTG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_el_load", models.FloatField(max_length=200)),
                ("recorded_ext_temp_gtg", models.FloatField(max_length=200)),
                ("recorded_amb_temp", models.FloatField(max_length=200)),
                (
                    "calculated_gtg_slip_ext",
                    models.FloatField(max_length=200, null=True),
                ),
                (
                    "calculation_time",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostCalculateLPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_lpc", models.FloatField(max_length=200)),
                ("recorded_air_pr_after_hpc", models.FloatField(max_length=200)),
                ("recorded_amb_pr_gtinlet", models.FloatField(max_length=200)),
                ("recorded_ext_temp", models.FloatField(max_length=200)),
                ("at_hpc_rpm", models.FloatField(max_length=200)),
                ("current_amb_temp", models.FloatField(max_length=200)),
                ("calculated_lpc_slip", models.FloatField(max_length=200, null=True)),
                ("calculated_air_slip", models.FloatField(max_length=200, null=True)),
                ("calculated_ext_slip", models.FloatField(max_length=200, null=True)),
                (
                    "calculation_time",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostEquipmentStateChangeHistorySave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_name", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("stop_time", models.DateTimeField(blank=True, null=True)),
                (
                    "started_at_location",
                    models.CharField(
                        choices=[
                            ("AT HARBOUR", "AT HARBOUR"),
                            ("AT SEA", "AT SEA"),
                            ("AT ANCHORAGE", "AT ANCHORAGE"),
                        ],
                        default="AT SEA",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("diff_in_hours", models.FloatField(max_length=200)),
                (
                    "entry_creation_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostRoutineDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_to_last_routine_running_hrs", models.FloatField(max_length=200)),
                (
                    "last_routine_due_running_hrs_ideal",
                    models.FloatField(blank=True, max_length=200, null=True),
                ),
                (
                    "last_routine_due_running_hrs_actual",
                    models.FloatField(blank=True, max_length=200, null=True),
                ),
                (
                    "last_to_last_routine_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_routine_date_ideal",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_routine_date_actual",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("hrs_between_two_routines", models.FloatField(max_length=200)),
                ("no_of_days_to_complete_routine", models.FloatField(max_length=200)),
                (
                    "entry_creation_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RADLMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ra_dl_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "dockyard_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "refit_type_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RADLRoutineDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("GENERATED", "GENERATED"),
                            ("APPROVED", "APPROVED"),
                            ("DELETED", "DELETED"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("dl_no", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "dl_type",
                    models.CharField(
                        choices=[
                            ("DL-I", "DL-I"),
                            ("DL-II", "DL-II"),
                            ("DL-III", "DL-III"),
                            ("RA", "RA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dl_key", models.CharField(blank=True, max_length=250, null=True)),
                ("ra_grup_id", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("additional_remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoutineDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintop_no", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "dart_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "routine_no",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("routine_description", models.TextField()),
                ("by_whom", models.CharField(max_length=1000)),
                ("is_fuss", models.BooleanField(default=False)),
                (
                    "last_routine_completion_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_routine_completion_atrunning_hrs",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "universal_id_t_dart",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_T_Dart",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "universal_id_t_routine_list",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dart_sr_no", models.CharField(blank=True, max_length=150, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("previous_completed_date", models.DateField(blank=True, null=True)),
                ("due_at_rh", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "previous_completed_at_rh",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_close", models.BooleanField(default=False)),
                ("is_greater_than_3_monthly", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("is_ra_initiate", models.BooleanField(default=False)),
                ("is_dl_initiate", models.BooleanField(default=False)),
                ("is_ra_draft", models.BooleanField(default=False)),
                ("is_dl_draft", models.BooleanField(default=False)),
                ("open_cmms_sync_date", models.DateField(blank=True, null=True)),
                ("close_cmms_sync_date", models.DateField(blank=True, null=True)),
                ("open_cmms_sync_status", models.BooleanField(default=False)),
                ("close_cmms_sync_status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SectionName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ShipMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ship_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SlipLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delta_n_lpc",
                    models.FloatField(blank=True, default=0, max_length=200, null=True),
                ),
                (
                    "delta_t_ext",
                    models.FloatField(blank=True, default=0, max_length=200, null=True),
                ),
                (
                    "delta_p_air",
                    models.FloatField(blank=True, default=0, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UniqueRoutineName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
