# Generated by Django 5.2.15 on 2026-08-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcalculatelpc",
            name="at_hpc_rpm",
            field=models.FloatField(db_column="at_HPC_rpm", max_length=200),
        ),
        migrations.AlterField(
            model_name="postcalculatelpc",
            name="recorded_lpc",
            field=models.FloatField(db_column="recorded_LPC", max_length=200),
        ),
    ]
