# Generated by Django 5.2.15 on 2026-08-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems", "0003_alter_postcalculatelpc_at_hpc_rpm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentname",
            name="universal_id_t_equipment_ship_detail",
            field=models.CharField(
                blank=True,
                db_column="Universal_ID_T_EquipmentShipDetail",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="routinedescription",
            name="universal_id_t_routine_list",
            field=models.CharField(
                blank=True,
                db_column="Universal_ID_T_RoutineList",
                max_length=100,
                null=True,
            ),
        ),
    ]
