# Generated by Django 5.2.15 on 2026-08-09 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chmastersymptoms",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_column="Department_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="master.department",
            ),
        ),
        migrations.AlterField(
            model_name="mdiagnostic",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_column="Department_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="master.department",
            ),
        ),
        migrations.AlterField(
            model_name="mrepair",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_column="Department_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="master.department",
            ),
        ),
    ]
