# Generated by Django 6.0.5 on 2026-08-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0003_alter_chmastersymptoms_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subdepartment",
            name="description",
            field=models.CharField(
                blank=True, db_column="Description", max_length=255, null=True
            ),
        ),
    ]
