# Generated by Django 5.2.15 on 2026-08-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0004_alter_subdepartment_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="subdepartment",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subdepartment",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="subdepartment",
            name="equipment_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subdepartment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
