# Generated by Django 5.2.15 on 2026-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_supplier_optional_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderduty',
            name='allocation_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single Day'), ('MULTIPLE', 'Multiple Day')], db_column='allocation_type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderduty',
            name='batch_id',
            field=models.CharField(blank=True, db_column='batch_id', help_text='Groups records from same Multiple Day submission', max_length=255, null=True),
        ),
    ]
