# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dart", "0002_initial"),
        ("ems", "0002_initial"),
        ("master", "0002_initial"),
        ("obs", "0001_initial"),
        ("sfd", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DartWedSpare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_date", models.DateField(auto_now_add=True, null=True)),
                ("modified_date", models.DateField(auto_now_add=True, null=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "dart_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="dart_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wed_spares",
                        to="dart.initiatedart",
                    ),
                ),
                (
                    "equipment_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="equipment_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dart_wed_spares",
                        to="sfd.shipequipment",
                    ),
                ),
                (
                    "issue_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="obs.issue",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_dartwedspare",
            },
        ),
        migrations.CreateModel(
            name="PlannedSparesDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spares_required", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "routine_description_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="routine_description_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wlms_planned_spares",
                        to="ems.routinedescription",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_plannedsparesdescription",
            },
        ),
        migrations.CreateModel(
            name="DemandDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("survey_no", models.CharField(blank=True, default="", max_length=200)),
                ("PTS_no", models.CharField(blank=True, default="", max_length=200)),
                ("demand_no", models.CharField(blank=True, default="", max_length=200)),
                (
                    "demand_qty",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_save", models.BooleanField(default=False)),
                ("is_demand", models.BooleanField(default=False)),
                ("is_sync", models.BooleanField(default=False)),
                ("sync_date", models.DateTimeField(blank=True, null=True)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "spare_cart_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "demand_pdf",
                    models.FileField(blank=True, null=True, upload_to="wed_demand/"),
                ),
                ("is_hod", models.BooleanField(default=False)),
                ("is_approval", models.BooleanField(default=False)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "wlms_demand_status",
                    models.CharField(default="Pending", max_length=200),
                ),
                (
                    "wed_demandno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "obs_spare_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="obs.spares",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "wed_dart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wlms.dartwedspare",
                    ),
                ),
                (
                    "wed_routine_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wlms.plannedsparesdescription",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_demanddetails",
            },
        ),
        migrations.CreateModel(
            name="PlannedWEDSpareList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_number",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("quantity_required", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "planned_spares_description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wlms.plannedsparesdescription",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_plannedwedsparelist",
            },
        ),
        migrations.CreateModel(
            name="PTSDemandDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("survey_no", models.CharField(blank=True, default="", max_length=200)),
                (
                    "PTS_demand_no",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("demand_no", models.CharField(blank=True, default="", max_length=200)),
                (
                    "demand_qty",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_save", models.BooleanField(default=False)),
                ("is_pts", models.BooleanField(default=False)),
                ("is_sync", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "spare_cart_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_hod", models.BooleanField(default=False)),
                ("is_approval", models.BooleanField(default=False)),
                ("sync_date", models.DateTimeField(blank=True, null=True)),
                (
                    "wlms_pts_status",
                    models.CharField(default="Pending", max_length=200),
                ),
                (
                    "wed_demandno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "obs_spare_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="obs.spares",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "wed_dart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wlms.dartwedspare",
                    ),
                ),
                (
                    "wed_routine_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wlms.plannedsparesdescription",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_ptsdemanddetails",
            },
        ),
        migrations.CreateModel(
            name="ReceiveDemandDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demand_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("demand_date", models.DateField(blank=True, null=True)),
                ("demand_quantity", models.IntegerField(default=0)),
                (
                    "original_demand_qty",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "demand_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "swmm_demandno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("dart_no", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gate_pass_no",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("gate_pass_date", models.DateTimeField(blank=True, null=True)),
                ("received_qty", models.IntegerField(blank=True, default=0, null=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                (
                    "demand_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wlms.demanddetails",
                    ),
                ),
                (
                    "pts_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wlms.ptsdemanddetails",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_receivedemanddetails",
            },
        ),
        migrations.CreateModel(
            name="SurveyReceiptsDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spare_cart_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_save", models.BooleanField(default=False)),
                ("is_survey", models.BooleanField(default=False)),
                ("is_sync", models.BooleanField(default=False)),
                ("is_hod", models.BooleanField(default=False)),
                ("is_approval", models.BooleanField(default=False)),
                (
                    "wlms_status",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("sync_date", models.DateTimeField(blank=True, null=True)),
                (
                    "wlms_survey_status",
                    models.CharField(default="Pending", max_length=200),
                ),
                (
                    "obs_spare_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="obs.spares",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "wed_dart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wlms.dartwedspare",
                    ),
                ),
                (
                    "wed_routine_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wlms.plannedsparesdescription",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_surveyreceiptsdetails",
            },
        ),
        migrations.CreateModel(
            name="SurveyFormsDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rece_qty", models.CharField(blank=True, default="", max_length=200)),
                (
                    "held_certificate_type",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "held_certificate_no",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("held_certificate_date", models.DateField(blank=True, null=True)),
                (
                    "held_certificate",
                    models.FileField(blank=True, null=True, upload_to="wed_survey/"),
                ),
                ("survey_no", models.CharField(blank=True, default="", max_length=200)),
                (
                    "wlms_survey_no",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "ss_remarks",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("scrap_qty", models.CharField(blank=True, default="", max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wed_servey_created",
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wed_servey_updated",
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "survey_rec_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wlms.surveyreceiptsdetails",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_surveyformsdetails",
            },
        ),
        migrations.CreateModel(
            name="WEDIIF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_sync", models.BooleanField(default=False)),
                ("is_hod", models.BooleanField(default=False)),
                ("is_approval", models.BooleanField(default=False)),
                ("sync_response", models.BooleanField(default=False)),
                ("is_delete", models.BooleanField(default=False)),
                ("sync_date", models.DateTimeField(blank=True, null=True)),
                (
                    "wlms_iif_status",
                    models.CharField(default="Pending", max_length=200),
                ),
                (
                    "spare_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="obs.spares",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.customuserprofile",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_wediif",
            },
        ),
        migrations.CreateModel(
            name="WEDIIFDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iif_no", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "comly_in_other_eqpt",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("annual_req", models.CharField(blank=True, max_length=200, null=True)),
                ("phone_no", models.IntegerField(blank=True, null=True)),
                (
                    "Specification",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "Qty_fitted_in_eqpt",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "iif_photo",
                    models.FileField(blank=True, null=True, upload_to="wed_iif/"),
                ),
                (
                    "proposed_MSL",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("drawing_no", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "drawing_doc",
                    models.FileField(blank=True, null=True, upload_to="wed_iif/"),
                ),
                (
                    "poev_costing_rs",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "bq_amount_rs",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "bq_doc",
                    models.FileField(blank=True, null=True, upload_to="wed_iif/"),
                ),
                ("ss_remarks", models.TextField(blank=True, null=True)),
                (
                    "wed_iif",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="wlms.wediif",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_wediifdetails",
            },
        ),
        migrations.CreateModel(
            name="WLMSEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eqpt_id", models.IntegerField(blank=True, null=True)),
                ("eqpt_name", models.CharField(blank=True, max_length=255, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("control_cell_id", models.IntegerField(blank=True, null=True)),
                ("sco_id", models.IntegerField(blank=True, null=True)),
                ("depot_id", models.IntegerField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wed_equipment_created",
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wed_equipment_updated",
                        to="users.customuserprofile",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_wlmsequipment",
            },
        ),
        migrations.CreateModel(
            name="WLMSSpare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wlms_inventory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("item_code", models.CharField(blank=True, max_length=100, null=True)),
                ("item_desc", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("denom_id", models.CharField(blank=True, max_length=100, null=True)),
                ("sh_name", models.CharField(blank=True, max_length=100, null=True)),
                ("latest_qty", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "typeofspare",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "denomination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wlms_spares",
                        to="obs.denomination",
                    ),
                ),
                (
                    "eqpt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wlms.wlmsequipment",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_wlmsspare",
            },
        ),
        migrations.AddField(
            model_name="surveyreceiptsdetails",
            name="wed_spares_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wlms.wlmsspare",
            ),
        ),
        migrations.CreateModel(
            name="SurveyFormsItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_serial_no",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "survey_details_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wlms.surveyformsdetails",
                    ),
                ),
                (
                    "wed_spares_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wlms.wlmsspare",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_surveyformsitems",
            },
        ),
        migrations.CreateModel(
            name="SpareDataMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wlms_spare_data_maps",
                        to="sfd.shipequipment",
                    ),
                ),
                (
                    "wed_equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spare_data_maps",
                        to="wlms.wlmsequipment",
                    ),
                ),
                (
                    "wed_spares",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spare_data_maps",
                        to="wlms.wlmsspare",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_sparedataMap",
            },
        ),
        migrations.AddField(
            model_name="ptsdemanddetails",
            name="wed_spares_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wlms.wlmsspare",
            ),
        ),
        migrations.AddField(
            model_name="plannedsparesdescription",
            name="wlms_spare_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wlms.wlmsspare",
            ),
        ),
        migrations.AddField(
            model_name="demanddetails",
            name="wed_spares_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wlms.wlmsspare",
            ),
        ),
        migrations.AddField(
            model_name="dartwedspare",
            name="wed_spare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wlms.wlmsspare",
            ),
        ),
        migrations.CreateModel(
            name="SignalDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demand_type",
                    models.CharField(
                        choices=[
                            ("OPDEM", "Operational Demand"),
                            ("STOREDEM", "Store Demand"),
                            ("CANDEM", "Cannibalisation Demand"),
                        ],
                        max_length=20,
                    ),
                ),
                ("demand_number", models.CharField(max_length=100)),
                ("dtg", models.DateTimeField()),
                (
                    "pts_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("demand_quantity", models.PositiveIntegerField(default=1)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="wlms/signal_demands/"
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("FORWARDED", "Forwarded"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REGISTERED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_signal_demands",
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "obs_spare",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wlms_signal_demands",
                        to="obs.spares",
                    ),
                ),
                (
                    "receiver_ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_cannibalisation_demands",
                        to="master.ship",
                    ),
                ),
                (
                    "requesting_ship",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raised_signal_demands",
                        to="master.ship",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signal_demands",
                        to="wlms.wlmsequipment",
                    ),
                ),
                (
                    "wed_spare",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signal_demands",
                        to="wlms.wlmsspare",
                    ),
                ),
            ],
            options={
                "db_table": "WLMS_signaldemand",
                "ordering": ["-dtg", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("demand_type", "demand_number"),
                        name="unique_wlms_signal_demand_number",
                    )
                ],
            },
        ),
    ]
