# Generated by Django 5.2.15 on 2026-08-08 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wlms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PTSItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_serial_no",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "pts_details_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wlms.ptsdemanddetails",
                    ),
                ),
                (
                    "wed_spares_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wlms.wlmsspare",
                    ),
                ),
            ],
        ),
    ]
