# Generated by Django 5.2.15 on 2026-08-09 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wlms", "0002_ptsitems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wlmsspare",
            name="denomination",
        ),
    ]
