# Generated by Django 5.2.15 on 2026-08-10 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dart", "0005_alter_dartspare_spare_id"),
        ("sfd", "0006_add_new_sfd_addon_fields_and_tables"),
        ("wlms", "0003_remove_wlmsspare_denomination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dartwedspare",
            name="dart_id",
            field=models.ForeignKey(
                blank=True,
                db_column="dart_id_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wed_spares",
                to="dart.initiatedart",
            ),
        ),
        migrations.AlterField(
            model_name="dartwedspare",
            name="equipment_id",
            field=models.ForeignKey(
                blank=True,
                db_column="equipment_id_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dart_wed_spares",
                to="sfd.shipequipment",
            ),
        ),
    ]
