upstream frontend {
    server swmm-frontend-dev:80;
    keepalive 32;
}

upstream backend {
    server swmm-backend-dev:8000;
    keepalive 32;
}

server {

    listen 80 default_server;

    server_name 172.16.50.7 _;

    location /api/ {

        proxy_pass http://backend;

        include /etc/nginx/proxy_params;
    }

    location /swagger/ {

        proxy_pass http://backend;

        include /etc/nginx/proxy_params;
    }

    location /schema/ {

        proxy_pass http://backend;

        include /etc/nginx/proxy_params;
    }

    location /admin/ {

        proxy_pass http://backend;

        include /etc/nginx/proxy_params;
    }

    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    location /media/ {
        alias /usr/share/nginx/html/media/;
    }

    location / {

        proxy_pass http://frontend;

        include /etc/nginx/proxy_params;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
