# Generated by Django 5.2.15 on 2026-08-08 09:51


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ilms", "0001_initial"),
        ("master", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy", models.CharField(max_length=255)),
                ("directive", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_type_id", models.CharField(max_length=255)),
                ("equipment_desc", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("cmms_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cmms_ship_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "equipment_category_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_a_user_created_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_a_user_updated_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "universal_id_ch_master_equipment_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("order_by", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["order_by"],
            },
        ),
        migrations.CreateModel(
            name="GenericSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SupplierID", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "SupplierCode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "SupplierName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("AreaStreet", models.CharField(blank=True, max_length=255, null=True)),
                ("City", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "CountryCode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("CountryID", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "SupplierManufacturer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("active", models.CharField(blank=True, max_length=255, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "updated_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Universal_ID_M_Supplier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Universal_ID_M_Country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "universal_id_a_user_created_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "universal_id_a_user_updated_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Contact_Person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Contact_Number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Email_ID", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "supplier_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("supplier_manufacture", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Generic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "specification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfd.genericspecification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ilms_eq_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "equipment_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("equipment_code", models.CharField(max_length=255)),
                (
                    "maintop_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "universal_id_m_equipment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "equipment_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "equipment_model",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "manufacturer_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("authority", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ilms_equipment_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfd.equipmentpolicy",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfd.equipmentspecification",
                    ),
                ),
                (
                    "generic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfd.generic",
                    ),
                ),
                (
                    "generic_specification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfd.genericspecification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SatelliteUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("code", models.CharField(max_length=15)),
                ("sequence", models.IntegerField(null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Active"), (2, "Inactive"), (3, "Delete")],
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("modified_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "command",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.command",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.customuserprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "satellite_unit",
                "verbose_name_plural": "satellite_units",
                "db_table": "master.satellite_units",
            },
        ),
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "command",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.command",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.ship",
                    ),
                ),
                (
                    "satellite_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sfd.satelliteunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Category",
                "verbose_name_plural": "Equipment Categories",
            },
        ),
        migrations.CreateModel(
            name="ShipEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "t_equipment_ship_detail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(default="active", max_length=100)),
                (
                    "equipment_serial_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "oem_part_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nomenclature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_on_board",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "compartment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("deck", models.CharField(blank=True, max_length=255, null=True)),
                ("frame", models.CharField(blank=True, max_length=255, null=True)),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("removal_date", models.DateField(blank=True, null=True)),
                ("no_of_fits", models.PositiveIntegerField(default=1)),
                (
                    "service_life",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("installation_remarks", models.TextField(blank=True, null=True)),
                ("is_srar", models.BooleanField(default=False)),
                (
                    "equipment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Parent", "Parent Equipment"),
                            ("Child", "Child Equipment"),
                        ],
                        default="Child",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "authority_installation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "authority_removal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("removal_remarks", models.TextField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("allocated_on", models.DateField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "ilms_vendor_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "system_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "eq_rhsi",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="RH Value at Installation",
                    ),
                ),
                ("rhsi_updated_until", models.DateTimeField(blank=True, null=True)),
                (
                    "eqp_specs",
                    models.TextField(
                        blank=True, null=True, verbose_name="Equipment Specification"
                    ),
                ),
                (
                    "insma_remarks",
                    models.TextField(
                        blank=True, null=True, verbose_name="INSMA remarks"
                    ),
                ),
                (
                    "request_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Request Reason"
                    ),
                ),
                (
                    "equipment_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="equipment_images/"
                    ),
                ),
                ("is_synced", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.department",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ship_allocations",
                        to="sfd.equipment",
                    ),
                ),
                (
                    "equipment_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfd.equipmentcategory",
                    ),
                ),
                (
                    "equipment_type_f_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfd.equipmenttype",
                    ),
                ),
                (
                    "ilms_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplied_equipments_sfd",
                        to="ilms.vendorlist",
                    ),
                ),
                (
                    "parent_equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_equipments",
                        to="sfd.equipment",
                    ),
                ),
                (
                    "satelite_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfd.satelliteunit",
                    ),
                ),
                (
                    "section_f_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.section",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="master.ship",
                    ),
                ),
                (
                    "sub_department_f_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.subdepartment",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplied_equipments_sfd",
                        to="sfd.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ship Equipment",
                "verbose_name_plural": "Ship Equipments",
                "db_table": "SFD_shipequipment",
            },
        ),
        migrations.CreateModel(
            name="EquipmentChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("removal_remark", models.TextField()),
                ("new_serial", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "rh_at_installation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("approved_reject", models.IntegerField(blank=True, null=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("amendment_note", models.TextField(blank=True, null=True)),
                ("is_synced", models.IntegerField(blank=True, null=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="request_equipment",
                        to="sfd.equipment",
                    ),
                ),
                (
                    "ship_equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ship_request_equipment",
                        to="sfd.shipequipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemoveEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("removal_remark", models.TextField()),
                ("removal_date", models.DateField(blank=True, null=True)),
                (
                    "authority_of_removal",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "equipment_serial_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("request_type", models.IntegerField(blank=True, null=True)),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("installation_remark", models.TextField(blank=True, null=True)),
                (
                    "rh_of_new_equipment_at_time_of_installation",
                    models.IntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("approved_reject", models.IntegerField(blank=True, null=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("amendment_note", models.TextField(blank=True, null=True)),
                ("is_synced", models.IntegerField(blank=True, null=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remove_request_equipment",
                        to="sfd.equipment",
                    ),
                ),
                (
                    "generic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sfd.generic",
                    ),
                ),
                (
                    "ship_equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remove_ship_request_equipment",
                        to="sfd.shipequipment",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplied_equipments",
                        to="sfd.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrialUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("code", models.CharField(max_length=15)),
                ("sequence", models.IntegerField(null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Active"), (2, "Inactive"), (3, "Delete")],
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("modified_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.customuserprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "trial_unit",
                "verbose_name_plural": "trial_units",
                "db_table": "master.trial_units",
            },
        ),
        migrations.AddField(
            model_name="shipequipment",
            name="trial_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sfd.trialunit",
            ),
        ),
        migrations.AddField(
            model_name="satelliteunit",
            name="trial_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sfd.trialunit",
            ),
        ),
        migrations.AddField(
            model_name="equipmentcategory",
            name="trial_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sfd.trialunit",
            ),
        ),
    ]
