# Generated by Django 5.2.15 on 2026-08-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sfd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmenttype",
            name="cmms_id",
            field=models.CharField(
                blank=True, db_column="CMMS_ID", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="cmms_ship_id",
            field=models.CharField(
                blank=True, db_column="CMMS_Ship_ID", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="equipment_category_code",
            field=models.CharField(
                blank=True,
                db_column="Equipment_Category_Code",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="equipment_desc",
            field=models.CharField(db_column="Equipment_Desc", max_length=255),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="equipment_type_id",
            field=models.CharField(db_column="Equipment_Type_ID", max_length=255),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="order_by",
            field=models.IntegerField(blank=True, db_column="Order_By", null=True),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="status",
            field=models.CharField(db_column="Status", max_length=50),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="universal_id_a_user_created_by",
            field=models.CharField(
                blank=True,
                db_column="Universal_ID_A_User_Created_By",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="universal_id_a_user_updated_by",
            field=models.CharField(
                blank=True,
                db_column="Universal_ID_A_User_Updated_By",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttype",
            name="universal_id_ch_master_equipment_type",
            field=models.CharField(
                blank=True,
                db_column="Universal_ID_Ch_Master_Equipment_Type",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="AreaStreet",
            field=models.CharField(
                blank=True, db_column="AreaStreet", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="City",
            field=models.CharField(
                blank=True, db_column="City", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="Contact_Number",
            field=models.CharField(
                blank=True, db_column="Contact_Number", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="Contact_Person",
            field=models.CharField(
                blank=True, db_column="Contact_Person", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="CountryCode",
            field=models.CharField(
                blank=True, db_column="CountryCode", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="CountryID",
            field=models.CharField(
                blank=True, db_column="CountryID", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="Email_ID",
            field=models.CharField(
                blank=True, db_column="Email_ID", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="SupplierCode",
            field=models.CharField(
                blank=True, db_column="SupplierCode", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="SupplierID",
            field=models.CharField(
                blank=True, db_column="SupplierID", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="SupplierManufacturer",
            field=models.CharField(
                blank=True, db_column="SupplierManufacturer", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="SupplierName",
            field=models.CharField(
                blank=True, db_column="SupplierName", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="Universal_ID_M_Country",
            field=models.CharField(
                blank=True,
                db_column="Universal_ID_M_Country",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="Universal_ID_M_Supplier",
            field=models.CharField(
                blank=True,
                db_column="Universal_ID_M_Supplier",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="active",
            field=models.CharField(
                blank=True, db_column="Active", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.CharField(
                blank=True, db_column="Address", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="created_by",
            field=models.CharField(
                blank=True, db_column="CreatedBy", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="created_date",
            field=models.CharField(
                blank=True, db_column="CreatedDate", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="universal_id_a_user_created_by",
            field=models.CharField(
                blank=True,
                db_column="Universal_ID_A_User_Created_By",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="universal_id_a_user_updated_by",
            field=models.CharField(
                blank=True,
                db_column="Universal_ID_A_User_Updated_By",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="updated_by",
            field=models.CharField(
                blank=True, db_column="UpdatedBy", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="updated_date",
            field=models.CharField(
                blank=True, db_column="UpdatedDate", max_length=255, null=True
            ),
        ),
        migrations.AlterModelTable(
            name="equipment",
            table="SFD_equipment",
        ),
        migrations.AlterModelTable(
            name="equipmentcategory",
            table="SFD_equipmentcategory",
        ),
        migrations.AlterModelTable(
            name="equipmentchangerequest",
            table="SFD_equipmentchangerequest",
        ),
        migrations.AlterModelTable(
            name="equipmentpolicy",
            table="SFD_equipmentpolicy",
        ),
        migrations.AlterModelTable(
            name="equipmentspecification",
            table="SFD_equipmentspecification",
        ),
        migrations.AlterModelTable(
            name="equipmenttype",
            table="SFD_equipment_type",
        ),
        migrations.AlterModelTable(
            name="generic",
            table="SFD_generic",
        ),
        migrations.AlterModelTable(
            name="genericspecification",
            table="SFD_genericspecification",
        ),
        migrations.AlterModelTable(
            name="removeequipment",
            table="SFD_removeeqipment",
        ),
        migrations.AlterModelTable(
            name="supplier",
            table="SFD_supplier",
        ),
    ]
