# Generated by Django 5.2.15 on 2026-08-09 05:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sfd", "0002_alter_equipmenttype_cmms_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="active",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="authority",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="equipment_model",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="equipment_name",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="ilms_equipment_code",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="manufacturer_name",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="updated_at",
        ),
    ]
