# Generated by Django 5.2.15 on 2026-08-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sfd", "0006_add_new_sfd_addon_fields_and_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="authority",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="manufacturer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="equipmentchangerequest",
            name="universal_id_a_user_created_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="equipmentchangerequest",
            name="universal_id_t_sfd_change_request",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="compartmentmaster",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("port_aft", "Port, Aft"),
                    ("port_forward", "Port, Forward"),
                    ("starboard_forward", "Starboard, Forward"),
                    ("starboard_aft", "Starboard, Aft"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="compartmentmaster",
            name="lower_deck",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deck1", "Deck 1"),
                    ("deck2", "Deck 2"),
                    ("deck3", "Deck 3"),
                    ("deck4", "Deck 4"),
                    ("deck5", "Deck 5"),
                    ("deck6", "Deck 6"),
                    ("deck7", "Deck 7"),
                    ("deck8", "Deck 8"),
                    ("deck9", "Deck 9"),
                    ("deck10", "Deck 10"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="compartmentmaster",
            name="upper_deck",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deck01", "Deck 01"),
                    ("deck02", "Deck 02"),
                    ("deck03", "Deck 03"),
                    ("deck04", "Deck 04"),
                    ("deck05", "Deck 05"),
                    ("deck06", "Deck 06"),
                    ("deck07", "Deck 07"),
                    ("deck08", "Deck 08"),
                    ("deck09", "Deck 09"),
                    ("deck10", "Deck 10"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shipequipment",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cat1", "Cat 1"),
                    ("cat2", "Cat 2"),
                    ("cat3", "Cat 3"),
                    ("survey", "Survey & Demand"),
                    ("other", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
