# Generated by Django 5.2.15 on 2026-08-12 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sfd", "0008_remap_legacy_choice_values"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="cmms_id",
            new_name="CMMS_ID",
        ),
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="cmms_ship_id",
            new_name="CMMS_Ship_ID",
        ),
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="equipment_category_code",
            new_name="Equipment_Category_Code",
        ),
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="equipment_desc",
            new_name="Equipment_Desc",
        ),
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="equipment_type_id",
            new_name="Equipment_Type_ID",
        ),
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="universal_id_ch_master_equipment_type",
            new_name="Universal_ID_Ch_Master_Equipment_Type",
        ),
    ]
