# Generated by Django 5.2.15 on 2026-08-13 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sfd", "0009_rename_cmms_id_equipmenttype_cmms_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="CMMS_ID",
            new_name="cmms_id",
        ),
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="CMMS_Ship_ID",
            new_name="cmms_ship_id",
        ),
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="Equipment_Category_Code",
            new_name="equipment_category_code",
        ),
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="Equipment_Desc",
            new_name="equipment_desc",
        ),
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="Equipment_Type_ID",
            new_name="equipment_type_id",
        ),
        migrations.RenameField(
            model_name="equipmenttype",
            old_name="Universal_ID_Ch_Master_Equipment_Type",
            new_name="universal_id_ch_master_equipment_type",
        ),
    ]
