# Generated by Django 5.2.15 on 2026-08-09 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dart", "0003_remove_initiatedart_aber_type_and_more"),
        ("obs", "0002_issue_is_deleted_issue_is_return_issue_is_wed_mo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempdartspare",
            name="issue_obj_id",
        ),
        migrations.RemoveField(
            model_name="tempdartspare",
            name="spare_id",
        ),
        migrations.AddField(
            model_name="tempdartspare",
            name="issue_obj",
            field=models.ForeignKey(
                blank=True,
                db_column="issue_obj_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="obs.issue",
            ),
        ),
        migrations.AddField(
            model_name="tempdartspare",
            name="spare",
            field=models.ForeignKey(
                blank=True,
                db_column="spare_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="obs.spares",
            ),
        ),
    ]
