# Generated by Django 5.2.15 on 2026-08-14 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dart", "0005_alter_dartspare_spare_id"),
        ("users", "0002_alter_loginregistrationimage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTypeMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now=True, null=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                ("modified_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "active",
                    models.SmallIntegerField(
                        choices=[(1, "active"), (2, "Inactive"), (3, "Delete")],
                        default=1,
                    ),
                ),
                ("certificate", models.CharField(max_length=10, unique=True)),
                ("meaning", models.CharField(max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_user",
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_modified_user",
                        to="users.customuserprofile",
                    ),
                ),
            ],
            options={
                "db_table": "dart_certificate_type_master",
            },
        ),
        migrations.CreateModel(
            name="ServiceMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now=True, null=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                ("modified_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "active",
                    models.SmallIntegerField(
                        choices=[(1, "active"), (2, "Inactive"), (3, "Delete")],
                        default=1,
                    ),
                ),
                ("service", models.CharField(max_length=100, unique=True)),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("requires_equipment", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_user",
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_modified_user",
                        to="users.customuserprofile",
                    ),
                ),
            ],
            options={
                "db_table": "dart_service_master",
            },
        ),
    ]
