# Generated by Django 5.2.15 on 2026-08-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dart", "0007_initiatedart_action_taken_to_repair_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiateradl",
            name="authority",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="initiateradl",
            name="ra_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="initiateradl",
            name="routing",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
