# Generated by Django 5.2.15 on 2026-08-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dart", "0008_initiateradl_authority_initiateradl_ra_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiatedart",
            name="exposure_pct",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="initiatedart",
            name="guarantee_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="initiatedart",
            name="risk",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="initiatedart",
            name="supplier",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
