from django.apps import apps
from django.contrib import admin
from django.contrib.admin.sites import AlreadyRegistered

from .models import (
    ChMasterShipRemarksBy,
    ChMasterSymptoms,
    CoMessage,
    Department,
    Frequency,
    HierarchyForChart,
    MaintenanceOccasionMaster,
    MDeferment,
    MDelay,
    MDiagnostic,
    MemberDetail,
    MEstablishment,
    MInability,
    MMaterialOrganizations,
    MRanklist,
    MReason,
    MRefit,
    MRefitCategory,
    MRepair,
    MRepairAgency,
    MRequiredAssistance,
    MSeverity,
    MShipCategory,
    MShipClass,
    MShipCommand,
    MShipOpsAuthority,
    MShipPropulsion,
    MShipUnitCategory,
    OpsMaintenancePeriod,
    OrderDuty,
    Quote,
    RefitMaintenancePeriod,
    Ship,
    ShipCategoryLookup,
    ShipClassLookup,
    ShipCommandLookup,
    ShipOpsAuthorityLookup,
    ShipPropulsionLookup,
    ShipRole,
    ShipRoleImage,
    SubDepartment,
    UpdateEntry,
)

MODELS = [
    Department,
    SubDepartment,
    Ship,
    OrderDuty,
    CoMessage,
    MShipCategory,
    MInability,
    MDelay,
    MDiagnostic,
    MRepairAgency,
    MRepair,
    MSeverity,
    MRanklist,
    MShipClass,
    MShipCommand,
    MShipOpsAuthority,
    MShipPropulsion,
    MShipUnitCategory,
    Frequency,
    ChMasterSymptoms,
    ChMasterShipRemarksBy,
    MRequiredAssistance,
    ShipCategoryLookup,
    ShipClassLookup,
    ShipCommandLookup,
    ShipOpsAuthorityLookup,
    ShipPropulsionLookup,
    UpdateEntry,
    Quote,
    ShipRole,
    ShipRoleImage,
    MemberDetail,
    HierarchyForChart,
    MRefitCategory,
    MRefit,
    OpsMaintenancePeriod,
    MMaterialOrganizations,
    MDeferment,
    RefitMaintenancePeriod,
    MEstablishment,
    MReason,
    MaintenanceOccasionMaster,
]

for model in MODELS:
    admin.site.register(model)

for model in apps.get_app_config("master").get_models():
    try:
        admin.site.register(model)
    except AlreadyRegistered:
        pass
