# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.db.models.deletion
import django.utils.timezone
import obs.models
import obs.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ems", "0002_initial"),
        ("master", "0002_initial"),
        ("sfd", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Authority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Denomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboard_denominations",
                        to="master.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "department")},
            },
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_issue",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date of Issue"
                    ),
                ),
                ("quantity_issued", models.PositiveSmallIntegerField(default=0)),
                ("issue_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=200)),
                (
                    "dart_number",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboard_spare_issues",
                        to="ems.equipmentname",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboard_spare_issues",
                        to="users.customuserprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_of_issue", "-id"],
            },
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IssueList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_toreturn", models.PositiveSmallIntegerField(default=0)),
                (
                    "dart_number",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "issue_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_list_entries",
                        to="obs.issue",
                    ),
                ),
            ],
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PlannedRoutineSpareList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_number",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("quantity_required", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "planned_routine_description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboard_spare_lists",
                        to="ems.plannedroutinedescription",
                    ),
                ),
            ],
            options={
                "db_table": "obs_planned_routine_spare_list",
                "ordering": ["pattern_number"],
            },
        ),
        migrations.CreateModel(
            name="PostDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_demanded", models.PositiveSmallIntegerField(default=0)),
                ("demand_number", models.SlugField(blank=True, default="")),
                ("demand_date", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=200)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("dart_number", models.TextField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_onboard_post_demands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_demands",
                        to="obs.issue",
                    ),
                ),
            ],
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SpareClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboard_spare_classes",
                        to="master.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "department")},
            },
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EquipmentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "spare_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_classes",
                        to="obs.spareclass",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "spare_class")},
            },
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Spares",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_number",
                    models.SlugField(blank=True, default="", max_length=500),
                ),
                ("description", models.CharField(default="", max_length=1000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "PERMANENT"),
                            ("RETURNABLE", "RETURNABLE"),
                            ("CONSUMABLE", "CONSUMABLE"),
                        ],
                        default="PERMANENT",
                        max_length=30,
                    ),
                ),
                ("critical", models.BooleanField(blank=True, default=False)),
                (
                    "compartment",
                    models.CharField(
                        blank=True, default="UNKNOWN", max_length=200, null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="UNKNOWN", max_length=200, null=True
                    ),
                ),
                (
                    "rack_position",
                    models.CharField(
                        blank=True, default="UNKNOWN", max_length=200, null=True
                    ),
                ),
                (
                    "rack_number",
                    models.CharField(
                        blank=True, default="UNKNOWN", max_length=200, null=True
                    ),
                ),
                (
                    "quantity_authorised",
                    models.PositiveSmallIntegerField(blank=True, default=0),
                ),
                (
                    "quantity_available",
                    models.PositiveSmallIntegerField(blank=True, default=0),
                ),
                (
                    "page",
                    models.SlugField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "line",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, default="", max_length=2000, null=True
                    ),
                ),
                (
                    "mo_demand_number",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="obs/default.png",
                        max_length=500,
                        null=True,
                        upload_to=obs.utils.spare_image_upload_path,
                    ),
                ),
                ("is_obs", models.BooleanField(default=False, null=True)),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spares",
                        to="obs.authority",
                    ),
                ),
                (
                    "denomination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spares",
                        to="obs.denomination",
                    ),
                ),
                (
                    "equipment_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spares",
                        to="obs.equipmentclass",
                    ),
                ),
            ],
            options={
                "ordering": ["pattern_number"],
            },
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RoutineSpareUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_used",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("date_used", models.DateField(auto_now_add=True)),
                (
                    "routine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboard_spare_usages",
                        to="ems.addroutinedetails",
                    ),
                ),
                (
                    "routine_description",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboard_spare_usages",
                        to="ems.routinedescription",
                    ),
                ),
                (
                    "spare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_usages",
                        to="obs.spares",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_used", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=200)),
                (
                    "remarks",
                    models.TextField(
                        blank=True, default="", max_length=2000, null=True
                    ),
                ),
                ("quantity_returned", models.PositiveSmallIntegerField(default=0)),
                ("return_time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "command_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboard_spare_returns",
                        to="master.mshipcommand",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboard_spare_returns",
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        db_column="ship_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboard_spare_returns",
                        to="master.ship",
                    ),
                ),
                (
                    "spare_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to="obs.spares",
                    ),
                ),
            ],
            options={
                "ordering": ["-return_time", "-id"],
            },
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Receive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_toreceive", models.PositiveSmallIntegerField(default=0)),
                ("dart_number", models.TextField(blank=True, null=True)),
                (
                    "demand_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receives",
                        to="obs.postdemand",
                    ),
                ),
                (
                    "issue_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receives",
                        to="obs.issue",
                    ),
                ),
                (
                    "spare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receives",
                        to="obs.spares",
                    ),
                ),
            ],
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PostSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_surveyed", models.PositiveSmallIntegerField(default=0)),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal Survey"),
                            ("OPDEM", "Operational Demand"),
                            ("PTS", "Provisioning Technical Specification"),
                            ("STOREDEM", "Store Demand"),
                            ("ONE_TIME_APPROVAL", "One-Time Approval"),
                        ],
                        default="NORMAL",
                        max_length=30,
                    ),
                ),
                ("survey_number", models.SlugField(blank=True, default="NA")),
                ("survey_report_date", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=200)),
                ("has_pts", models.BooleanField(blank=True, default=False)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("dart_number", models.TextField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_onboard_post_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_surveys",
                        to="obs.issue",
                    ),
                ),
                (
                    "spare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="post_surveys",
                        to="obs.spares",
                    ),
                ),
            ],
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PostReceive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_received", models.PositiveSmallIntegerField(default=0)),
                ("receipt_number", models.SlugField(blank=True, default="")),
                ("receive_date", models.DateTimeField(blank=True, null=True)),
                (
                    "nac_status",
                    models.BooleanField(
                        blank=True,
                        choices=[(False, "NO"), (True, "YES")],
                        default=False,
                    ),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=200)),
                ("dart_number", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_onboard_post_receives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_receives",
                        to="obs.issue",
                    ),
                ),
                (
                    "spare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="post_receives",
                        to="obs.spares",
                    ),
                ),
            ],
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.AddField(
            model_name="postdemand",
            name="spare",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="post_demands",
                to="obs.spares",
            ),
        ),
        migrations.CreateModel(
            name="NotInCattedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incatted_status", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "spare_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="not_in_catted_items",
                        to="obs.spares",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="issue",
            name="spare",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="obs.spares",
            ),
        ),
        migrations.CreateModel(
            name="Demand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_todemand", models.PositiveSmallIntegerField(default=0)),
                ("dart_number", models.TextField(blank=True, null=True)),
                ("is_iif", models.BooleanField(blank=True, default=False)),
                ("is_iif_sync", models.BooleanField(blank=True, default=False)),
                (
                    "issue_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demands",
                        to="obs.issue",
                    ),
                ),
                (
                    "survey_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demands",
                        to="obs.postsurvey",
                    ),
                ),
                (
                    "spare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demands",
                        to="obs.spares",
                    ),
                ),
            ],
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SparesMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obs_mappings",
                        to="sfd.shipequipment",
                    ),
                ),
                (
                    "equipment_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spares_mappings",
                        to="obs.equipmentclass",
                    ),
                ),
                (
                    "section_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obs_mappings",
                        to="master.section",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_tosurvey", models.PositiveSmallIntegerField(default=0)),
                ("dart_number", models.TextField(blank=True, null=True)),
                ("is_iif", models.BooleanField(blank=True, default=False)),
                ("is_iif_sync", models.BooleanField(blank=True, default=False)),
                (
                    "issue_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="obs.issue",
                    ),
                ),
                (
                    "spare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveys",
                        to="obs.spares",
                    ),
                ),
            ],
            bases=(obs.models.UppercaseCleanMixin, models.Model),
        ),
    ]
