# Generated by Django 5.2.15 on 2026-08-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_return",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_wed_mo",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
