# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompleteDefectDart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.CharField(db_column="serial_no", max_length=200)),
                (
                    "dart_no",
                    models.CharField(
                        blank=True, db_column="dart_no", max_length=200, null=True
                    ),
                ),
                (
                    "rectified_date",
                    models.DateField(blank=True, db_column="rectified_date", null=True),
                ),
                (
                    "days_delay",
                    models.IntegerField(blank=True, db_column="days_delay", null=True),
                ),
                (
                    "spares_delay",
                    models.IntegerField(
                        blank=True, db_column="spares_delay", null=True
                    ),
                ),
                (
                    "other_reasons",
                    models.TextField(blank=True, db_column="other_reasons", null=True),
                ),
                (
                    "lesson_learnt",
                    models.TextField(blank=True, db_column="lesson_learnt", null=True),
                ),
                (
                    "defect_report",
                    models.FileField(
                        blank=True,
                        db_column="defect_report",
                        null=True,
                        upload_to="defect_reports/",
                    ),
                ),
            ],
            options={
                "db_table": "dart_complete_defect_dart",
            },
        ),
        migrations.CreateModel(
            name="CompletedRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_dart_number",
                    models.CharField(
                        db_column="old_dart_number", default="", max_length=200
                    ),
                ),
                (
                    "new_dart_number",
                    models.CharField(
                        db_column="new_dart_number", default="", max_length=200
                    ),
                ),
                (
                    "date_of_completion",
                    models.DateField(
                        blank=True, db_column="date_of_completion", null=True
                    ),
                ),
                (
                    "hours",
                    models.IntegerField(blank=True, db_column="hours", null=True),
                ),
                (
                    "minutes",
                    models.IntegerField(blank=True, db_column="minutes", null=True),
                ),
                (
                    "carried_by",
                    models.CharField(
                        blank=True, db_column="carried_by", max_length=200, null=True
                    ),
                ),
                (
                    "p_no",
                    models.CharField(
                        blank=True, db_column="p_no", max_length=50, null=True
                    ),
                ),
                (
                    "other_rank",
                    models.CharField(
                        blank=True, db_column="other_rank", max_length=100, null=True
                    ),
                ),
                (
                    "total_manpower",
                    models.IntegerField(
                        blank=True, db_column="total_manpower", null=True
                    ),
                ),
                (
                    "running_hour",
                    models.CharField(
                        blank=True, db_column="running_hour", max_length=100, null=True
                    ),
                ),
                (
                    "due_running_hour",
                    models.CharField(
                        blank=True,
                        db_column="due_running_hour",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "repair_remark",
                    models.TextField(blank=True, db_column="repair_remark", null=True),
                ),
                (
                    "completion_details",
                    models.TextField(
                        blank=True, db_column="completion_details", null=True
                    ),
                ),
                ("trial_team", models.BooleanField(default=False)),
                ("rec_for_deletion", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "isfuss_close",
                    models.BooleanField(db_column="isfuss_close", default=False),
                ),
                (
                    "not_applicable",
                    models.BooleanField(db_column="not_applicable", default=False),
                ),
                (
                    "rec_deletion",
                    models.BooleanField(db_column="rec_deletion", default=False),
                ),
                (
                    "old_universal_id_t_dart",
                    models.CharField(
                        blank=True, db_column="old_universal_id_t_dart", null=True
                    ),
                ),
            ],
            options={
                "db_table": "dart_completedroutine",
            },
        ),
        migrations.CreateModel(
            name="CompletedRoutineSpare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spare_name",
                    models.CharField(db_column="spare_name", max_length=200),
                ),
            ],
            options={
                "db_table": "dart_completedroutine_spare",
            },
        ),
        migrations.CreateModel(
            name="DartSpare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spare_id", models.IntegerField(blank=True, null=True)),
                ("pattern", models.CharField(db_column="pattern", max_length=255)),
                (
                    "inventory_type",
                    models.CharField(
                        blank=True,
                        db_column="inventory_type",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(db_column="description")),
                (
                    "quantity",
                    models.PositiveIntegerField(db_column="quantity", default=1),
                ),
                (
                    "is_delete",
                    models.BooleanField(db_column="is_delete", default=False),
                ),
            ],
            options={
                "db_table": "dart_dartspare",
            },
        ),
        migrations.CreateModel(
            name="DartSpareUsed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_no",
                    models.CharField(
                        blank=True, db_column="pattern_no", max_length=255, null=True
                    ),
                ),
                ("description", models.TextField(db_column="description")),
                (
                    "quantity",
                    models.PositiveIntegerField(db_column="quantity", default=1),
                ),
            ],
            options={
                "db_table": "dart_dartspareused",
            },
        ),
        migrations.CreateModel(
            name="InitiateDart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dart_number",
                    models.CharField(
                        blank=True, db_column="dart_number", max_length=200, null=True
                    ),
                ),
                (
                    "dart_sr_number",
                    models.CharField(
                        blank=True,
                        db_column="dart_sr_number",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "dart_date",
                    models.DateField(blank=True, db_column="dart_date", null=True),
                ),
                ("rectification_date", models.DateField(blank=True, null=True)),
                (
                    "ops_status",
                    models.BooleanField(blank=True, db_column="ops_status", null=True),
                ),
                (
                    "trial_required",
                    models.BooleanField(
                        blank=True, db_column="trial_required", null=True
                    ),
                ),
                (
                    "defective_discriptions",
                    models.TextField(
                        blank=True,
                        db_column="defective_discriptions",
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(600)],
                    ),
                ),
                (
                    "defective_component",
                    models.CharField(
                        blank=True,
                        db_column="defective_component",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "rha_defect",
                    models.CharField(
                        blank=True, db_column="RHA_defect", max_length=200, null=True
                    ),
                ),
                (
                    "universal_id_trial_required",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "universal_id_t_dart",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_closed", models.BooleanField(default=False)),
                ("sapres_required", models.BooleanField(default=False)),
                (
                    "photograph",
                    models.FileField(blank=True, null=True, upload_to="dart_photos/"),
                ),
                ("created_date", models.DateField(auto_now_add=True, null=True)),
                ("is_ra_initiate", models.BooleanField(default=False)),
                ("is_dl_initiate", models.BooleanField(default=False)),
                ("is_ra_draft", models.BooleanField(default=False)),
                ("is_dl_draft", models.BooleanField(default=False)),
                (
                    "maintenance_period",
                    models.CharField(
                        blank=True,
                        db_column="maintenance_period",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dart_occasion",
                    models.CharField(
                        blank=True, db_column="dart_occasion", max_length=100, null=True
                    ),
                ),
                (
                    "cmms_sync_date",
                    models.DateField(blank=True, db_column="cmms_sync_date", null=True),
                ),
                (
                    "cmms_sync_status",
                    models.BooleanField(db_column="cmms_sync_status", default=False),
                ),
                (
                    "is_guarantee_defect",
                    models.BooleanField(db_column="is_guarantee_defect", default=False),
                ),
                (
                    "guarantee_cause",
                    models.TextField(
                        blank=True, db_column="guarantee_cause", null=True
                    ),
                ),
                (
                    "guarantee_op_availability",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "guarantee_hot_work",
                    models.BooleanField(
                        blank=True,
                        db_column="guarantee_hot_work",
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "guarantee_repairs",
                    models.TextField(
                        blank=True, db_column="guarantee_repairs", null=True
                    ),
                ),
                (
                    "guarantee_completion_date",
                    models.DateField(
                        blank=True, db_column="guarantee_completion_date", null=True
                    ),
                ),
                (
                    "guarantee_repair_date",
                    models.DateField(
                        blank=True, db_column="guarantee_repair_date", null=True
                    ),
                ),
                (
                    "guarantee_place",
                    models.TextField(
                        blank=True, db_column="guarantee_place", null=True
                    ),
                ),
                (
                    "aber_type",
                    models.CharField(
                        blank=True, db_column="aber_type", max_length=50, null=True
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True, db_column="authority", max_length=255, null=True
                    ),
                ),
                (
                    "previous_dart_no",
                    models.CharField(
                        blank=True,
                        db_column="previous_dart_no",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, db_column="remarks", null=True),
                ),
            ],
            options={
                "db_table": "dart_initiate_dart",
            },
        ),
        migrations.CreateModel(
            name="InitiateRADL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("GENERATED", "GENERATED"),
                            ("APPROVED", "APPROVED"),
                            ("DELETED", "DELETED"),
                        ],
                        db_column="status",
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                (
                    "dl_no",
                    models.CharField(
                        blank=True, db_column="dl_no", max_length=250, null=True
                    ),
                ),
                (
                    "dl_type",
                    models.CharField(
                        choices=[
                            ("DL-II", "DL-II"),
                            ("DL-III", "DL-III"),
                            ("RA", "RA"),
                        ],
                        db_column="dl_type",
                        max_length=20,
                    ),
                ),
                (
                    "dl_key",
                    models.CharField(
                        blank=True, db_column="dl_key", max_length=250, null=True
                    ),
                ),
                (
                    "ra_grup_id",
                    models.CharField(db_column="ra_grup_id", max_length=100),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, db_column="remarks", null=True),
                ),
                (
                    "additional_remarks",
                    models.TextField(
                        blank=True, db_column="additional_remarks", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dart_initiateradl",
            },
        ),
        migrations.CreateModel(
            name="RADLMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ra_dl_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "dockyard_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "refit_type_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dart_radlmaster",
            },
        ),
        migrations.CreateModel(
            name="TCandef",
            fields=[
                (
                    "universal_id_t_candef",
                    models.CharField(
                        db_column="Universal_ID_T_Candef",
                        max_length=500,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "candef_number",
                    models.CharField(
                        blank=True, db_column="CandefNumber", max_length=500, null=True
                    ),
                ),
                (
                    "sr_no",
                    models.CharField(
                        blank=True, db_column="SrNo", max_length=500, null=True
                    ),
                ),
                (
                    "ship_sr_no",
                    models.CharField(
                        blank=True, db_column="ShipSrNo", max_length=500, null=True
                    ),
                ),
                (
                    "equipment_code",
                    models.CharField(
                        blank=True, db_column="EquipmentCode", max_length=500, null=True
                    ),
                ),
                (
                    "department_id",
                    models.CharField(
                        blank=True, db_column="DepartmentID", max_length=500, null=True
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, db_column="Department", max_length=500, null=True
                    ),
                ),
                (
                    "ex_dept",
                    models.CharField(
                        blank=True, db_column="ExDept", max_length=500, null=True
                    ),
                ),
                (
                    "ex_dept_id",
                    models.CharField(
                        blank=True, db_column="ExDeptID", max_length=500, null=True
                    ),
                ),
                (
                    "candef_date",
                    models.CharField(
                        blank=True, db_column="CandefDate", max_length=100, null=True
                    ),
                ),
                (
                    "defect_date",
                    models.CharField(
                        blank=True, db_column="DefectDate", max_length=100, null=True
                    ),
                ),
                (
                    "schedule_date",
                    models.CharField(
                        blank=True, db_column="ScheduleDate", max_length=100, null=True
                    ),
                ),
                (
                    "universal_id_ch_master_symptoms",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_Ch_Master_Symptoms",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "severity_id",
                    models.CharField(
                        blank=True, db_column="SeverityID", max_length=500, null=True
                    ),
                ),
                (
                    "severity_code",
                    models.CharField(
                        blank=True, db_column="SeverityCode", max_length=500, null=True
                    ),
                ),
                (
                    "universal_id_m_severity",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_M_Severity",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "universal_id_ch_master_ship_remarks_by",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_Ch_Master_Ship_Remarks_By",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "universal_id_m_required_assistance",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_M_RequiredAssistance",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_ost_observation",
                    models.CharField(
                        blank=True,
                        db_column="IsOstObservation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "universal_id_m_ost_list",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_M_OSTList",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "defective_component",
                    models.CharField(
                        blank=True,
                        db_column="DefectiveComponent",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, db_column="Remarks", null=True),
                ),
                (
                    "defect_description",
                    models.TextField(
                        blank=True, db_column="DefectDescription", null=True
                    ),
                ),
                ("is_closed", models.IntegerField(db_column="IsClosed", default=0)),
                ("is_defect", models.IntegerField(db_column="Is_Defect", default=1)),
                ("active", models.IntegerField(db_column="Active", default=1)),
                ("nil_dart", models.IntegerField(db_column="NILDart", default=0)),
                ("is_amp", models.IntegerField(db_column="Is_Amp", default=0)),
                (
                    "is_signal_drafted",
                    models.IntegerField(db_column="Is_Signal_Drafted", default=0),
                ),
                ("is_refit", models.IntegerField(db_column="Is_Refit", default=0)),
                ("is_routine", models.IntegerField(db_column="Is_Routine", default=0)),
                (
                    "is_dl_ii_drafted",
                    models.IntegerField(db_column="Is_DLIIDrafted", default=0),
                ),
                (
                    "is_refit_ra_draft",
                    models.IntegerField(db_column="Is_RefitRADraft", default=0),
                ),
                ("is_gd_form", models.IntegerField(db_column="IsGDForm", default=0)),
                (
                    "universal_id_m_ship",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_M_Ship",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "universal_id_m_department",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_M_Department",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "universal_id_t_equipment_ship_detail",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_T_EquipmentShipDetail",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "created_date",
                    models.CharField(
                        blank=True, db_column="CreatedDate", max_length=100, null=True
                    ),
                ),
                (
                    "routine_defect",
                    models.IntegerField(db_column="RoutineDefect", default=2),
                ),
                (
                    "is_final_submit",
                    models.IntegerField(db_column="Is_Final_Submit", default=1),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, db_column="Serial_Number", max_length=500, null=True
                    ),
                ),
                (
                    "is_operational",
                    models.CharField(
                        blank=True,
                        db_column="Is_Operational",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "universal_id_t_ref_comp",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_T_RefComp",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "rectified_date",
                    models.CharField(
                        blank=True, db_column="RectifiedDate", max_length=100, null=True
                    ),
                ),
                (
                    "cancel_date",
                    models.CharField(
                        blank=True, db_column="CancelDate", max_length=100, null=True
                    ),
                ),
                (
                    "diagnostic_code",
                    models.CharField(
                        blank=True,
                        db_column="DiagnosticCode",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "repair_code",
                    models.CharField(
                        blank=True, db_column="RepairCode", max_length=500, null=True
                    ),
                ),
                (
                    "delay_reason_days",
                    models.IntegerField(
                        blank=True, db_column="DelayReasonDays", null=True
                    ),
                ),
                (
                    "additional_remarks",
                    models.TextField(
                        blank=True, db_column="Additional_Remarks", null=True
                    ),
                ),
                (
                    "spares_availability",
                    models.IntegerField(
                        blank=True, db_column="SparesAvailability", null=True
                    ),
                ),
                (
                    "diagnostic_id",
                    models.IntegerField(
                        blank=True, db_column="DiagnosticID", null=True
                    ),
                ),
                (
                    "repair_id",
                    models.IntegerField(blank=True, db_column="RepairID", null=True),
                ),
                (
                    "repair_agency_id",
                    models.IntegerField(
                        blank=True, db_column="RepairAgencyID", null=True
                    ),
                ),
                (
                    "agency_code",
                    models.CharField(
                        blank=True, db_column="AgencyCode", max_length=500, null=True
                    ),
                ),
                (
                    "delay_id",
                    models.IntegerField(blank=True, db_column="DelayID", null=True),
                ),
                (
                    "delay_code",
                    models.CharField(
                        blank=True, db_column="DelayCode", max_length=500, null=True
                    ),
                ),
                (
                    "universal_id_m_repair",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_M_Repair",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "universal_id_m_delay",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_M_Delay",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "universal_id_m_diagnostic",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_M_Diagnostic",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "universal_id_m_repair_agency",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_M_RepairAgency",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_auto_generated_dart",
                    models.IntegerField(
                        blank=True, db_column="Is_Auto_Generated_Dart", null=True
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, db_column="UpdatedDate"),
                ),
            ],
            options={
                "db_table": "T_Candef",
            },
        ),
        migrations.CreateModel(
            name="TempDartSpare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_obj_id", models.IntegerField(blank=True, null=True)),
                ("spare_id", models.IntegerField(blank=True, null=True)),
                ("pattern", models.CharField(db_column="pattern", max_length=255)),
                ("description", models.TextField(db_column="description")),
                (
                    "quantity",
                    models.PositiveIntegerField(db_column="quantity", default=1),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, db_column="created_date", null=True
                    ),
                ),
                (
                    "modified_date",
                    models.DateField(
                        auto_now_add=True, db_column="modified_date", null=True
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(db_column="is_delete", default=False),
                ),
            ],
            options={
                "db_table": "dart_tempdartspare",
            },
        ),
    ]
