# Generated by Django 5.2.15 on 2026-08-09 05:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dart", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="initiatedart",
            name="aber_type",
        ),
        migrations.RemoveField(
            model_name="initiatedart",
            name="authority",
        ),
        migrations.RemoveField(
            model_name="initiatedart",
            name="previous_dart_no",
        ),
        migrations.RemoveField(
            model_name="initiatedart",
            name="remarks",
        ),
    ]
