# Generated by Django 5.2.15 on 2026-08-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dart", "0004_remove_tempdartspare_issue_obj_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dartspare",
            name="spare_id",
            field=models.IntegerField(blank=True, db_column="spare_id_id", null=True),
        ),
    ]
