# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="role_hierarchy",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "role_hierarchy",
            },
        ),
        migrations.CreateModel(
            name="RoleMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(default="", max_length=100)),
                ("lastname", models.CharField(blank=True, default="", max_length=100)),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("personal_number", models.SlugField(default="", max_length=15)),
                ("section", models.CharField(blank=True, default="", max_length=50)),
                (
                    "ship_joining_date",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("ship_leaving_date", models.DateTimeField(null=True)),
                ("remarks", models.CharField(default="", max_length=200)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("0", "ADMINISTRATOR"),
                            ("1", "SUPERUSER"),
                            ("2", "STOREKEEPER"),
                            ("3", "OTHERS"),
                        ],
                        default="2",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "executive_sub_department",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("has_credentials", models.BooleanField(default=False, null=True)),
                ("is_role", models.BooleanField(default=False, null=True)),
                ("user_created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("user_active", models.BooleanField(default=True)),
                ("is_ood", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "is_regulator",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                (
                    "is_married",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("marriage_date", models.DateField(blank=True, null=True)),
                (
                    "command_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_command",
                        to="master.mastercommand",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.department",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.ship",
                    ),
                ),
                (
                    "designation_master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.customuserprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("title", models.CharField(max_length=200)),
                ("caption", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.department",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.ship",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginRegistrationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload login page image", upload_to="login_images/"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional image name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="login-registration-image", max_length=100
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_login_images",
                        to="users.customuserprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Registration Image",
                "verbose_name_plural": "Login Registration Images",
                "db_table": "login_registration_images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MasterRegulatorDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division", models.CharField(max_length=255)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.department",
                    ),
                ),
                (
                    "regulator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulator_divisions",
                        to="users.customuserprofile",
                    ),
                ),
            ],
            options={
                "db_table": "master_regulator_division",
            },
        ),
        migrations.CreateModel(
            name="MasterKnowYourRegulator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.department",
                    ),
                ),
                (
                    "regulator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="know_regulator",
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "sailor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="division_sailor",
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.masterregulatordivision",
                    ),
                ),
            ],
            options={
                "db_table": "master_know_your_regulator",
            },
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sailors",
                to="users.masterregulatordivision",
            ),
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherCustomUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("personal_number", models.CharField(max_length=50, unique=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("section", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("0", "ADMINISTRATOR"),
                            ("1", "SUPERUSER"),
                            ("2", "STOREKEEPER"),
                            ("3", "OTHERS"),
                        ],
                        default="3",
                        max_length=2,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_profiles",
                        to="users.customuserprofile",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.department",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.rank",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.rank",
            ),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="role_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.role",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customuserprofile",
            unique_together={("personal_number", "ship_joining_date")},
        ),
    ]
