# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryName",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
                ("is_system", models.BooleanField(default=False)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "dms_category_name",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("other", "Other"),
                            ("correspondence", "Correspondence"),
                            ("sharepoint", "Sharepoint"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "certificate_subtype",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "certificate_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "place_of_issue",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("letter_description", models.TextField(blank=True, null=True)),
                ("letter_received_on", models.DateField(blank=True, null=True)),
                ("letter_date", models.DateField(blank=True, null=True)),
                (
                    "letter_ref_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recieved_from_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("replied", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "addressed_to_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("equipment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "equipment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user_department",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("filenumber", models.CharField(blank=True, max_length=255, null=True)),
                ("ship", models.CharField(blank=True, max_length=255, null=True)),
                ("command", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "outmail_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_shared", models.BooleanField(default=False)),
                ("shared_on", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Equipment Category",
                "verbose_name_plural": "Equipment Categories",
                "db_table": "dms_equipment_category",
                "ordering": ["equipment_name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                ("document_type", models.CharField(max_length=100)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="equipment_documents/%Y/%m/"
                    ),
                ),
                ("uploaded_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Equipment Document",
                "verbose_name_plural": "Equipment Documents",
                "db_table": "dms_equipment_document",
                "ordering": ["-uploaded_date"],
            },
        ),
    ]
