# Generated by Django 5.2.15 on 2026-08-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dms", "0001_initial"),
        ("master", "0002_initial"),
        ("sfd", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="linked_command",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dms_certificates",
                to="master.mshipcommand",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="linked_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dms_certificates",
                to="master.department",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="linked_equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dms_certificates",
                to="sfd.shipequipment",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="linked_ship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dms_certificates",
                to="master.ship",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_certificates",
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="equipmentcategory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="equipmentdocument",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.customuserprofile",
            ),
        ),
        migrations.AddField(
            model_name="equipmentdocument",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="dms.equipmentcategory",
            ),
        ),
    ]
